import { Component, OnInit, signal } from "@angular/core";
import { IonSpinner } from "@ionic/angular/standalone";
import { StaffAppService, StaffEnterpriseOs } from "../../core/staff-app.service";

@Component({ standalone: true, imports: [IonSpinner], template: `
  <section class="page"><header class="page-head"><div><p class="eyebrow">Learning</p><h1>Learning center</h1><p>Badges, coaching cues and suggested learning focus.</p></div></header>
  @if (loading()) { <section class="state"><ion-spinner name="crescent" /> Loading learning center...</section> } @if (staff.error()) { <section class="notice">{{ staff.error() }}</section> }
  @if (os(); as data) { <section class="grid four"><article class="kpi"><span>Progress</span><strong>{{ learningProgress() }}%</strong></article><article class="kpi"><span>Badges</span><strong>{{ earnedBadges() }}/{{ data.gamification.badges.length }}</strong></article><article class="kpi"><span>Level</span><strong>{{ data.gamification.level }}</strong></article><article class="kpi"><span>Streak</span><strong>{{ data.gamification.monthlyStreak }}</strong></article></section><section class="panel"><div class="panel-title"><h2>Learning progress</h2><span>{{ learningProgress() }}%</span></div><div class="timer-track"><span [style.width.%]="learningProgress()"></span></div></section><section class="grid two"><article class="panel"><div class="panel-title"><h2>Earned badges</h2><span>{{ data.gamification.badges.length }}</span></div><div class="row-actions">@for (badge of data.gamification.badges; track badge.label) { <span class="badge" [class.green]="badge.earned">{{ badge.label }}</span> }</div></article><article class="panel"><div class="panel-title"><h2>Learning focus</h2><span>AI</span></div>@for (item of data.performance.opportunities; track item) { <p class="insight">{{ item }}</p> } @empty { <p class="empty">No learning gaps detected.</p> }</article></section> }
  </section>`, styleUrls: ["./staff-app.styles.css"] })
export class StaffLearningPage implements OnInit { readonly os = signal<StaffEnterpriseOs | null>(null); readonly loading = signal(false); constructor(readonly staff: StaffAppService) {} ngOnInit() { void this.load(); } async load() { this.loading.set(true); try { this.os.set(await this.staff.enterpriseOs()); } finally { this.loading.set(false); } } earnedBadges(): number { return (this.os()?.gamification.badges || []).filter((badge) => badge.earned).length; } learningProgress(): number { const badges = this.os()?.gamification.badges || []; return badges.length ? Math.round((this.earnedBadges() / badges.length) * 100) : 0; } }
