import { DatePipe } from "@angular/common";
import { Component, OnInit, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { IonSpinner } from "@ionic/angular/standalone";
import { StaffAppService, StaffLeave, StaffLeaveBalance } from "../../core/staff-app.service";

@Component({ standalone: true, imports: [DatePipe, FormsModule, IonSpinner], template: `
  <section class="page"><header class="page-head"><div><p class="eyebrow">Leaves</p><h1>Leave management</h1><p>Balances, history and request form.</p></div></header>
  @if (!staff.hasPermission('read:staff')) { <section class="notice">You do not have permission to view leave data.</section> }
  @if (loading()) { <section class="state"><ion-spinner name="crescent" /> Loading leaves...</section> } @if (message()) { <section class="notice success">{{ message() }}</section> } @if (staff.error()) { <section class="notice">{{ staff.error() }}</section> }
  @if (staff.hasPermission('read:staff')) { <section class="grid two"><article class="panel"><div class="panel-title"><h2>Leave balance</h2><span>{{ balances().length }}</span></div><div class="list">@for (balance of balances(); track balance.id) { <div class="row"><strong>{{ balance.leaveType }}</strong><span>{{ leaveBalanceValue(balance) }} left</span></div> } @empty { <p class="empty">No leave balances configured.</p> }</div></article><article class="panel"><div class="panel-title"><h2>Leave history</h2><span>{{ leaves().length }}</span></div><div class="list">@for (leave of leaves(); track leave.id) { <div class="row"><div class="row-main"><strong>{{ leave.leaveType }} · {{ leave.days || 1 }}d</strong><small>{{ leave.startDate | date:'mediumDate' }} - {{ leave.endDate | date:'mediumDate' }}</small></div><span class="badge">{{ leave.status }}</span></div> } @empty { <p class="empty">No leave requests yet.</p> }</div></article></section><section class="panel"><div class="panel-title"><h2>Request leave</h2><span>form</span></div><div class="form-grid"><label>Type<input [(ngModel)]="leaveType" placeholder="casual" /></label><label>From<input [(ngModel)]="leaveStart" type="date" /></label><label>To<input [(ngModel)]="leaveEnd" type="date" /></label><label>Reason<input [(ngModel)]="leaveReason" placeholder="Reason" /></label></div><button class="link-button" type="button" (click)="requestLeave()">Send request</button></section> }
  </section>`, styleUrls: ["./staff-app.styles.css"] })
export class StaffLeavesPage implements OnInit { readonly leaves = signal<StaffLeave[]>([]); readonly balances = signal<StaffLeaveBalance[]>([]); readonly loading = signal(false); readonly message = signal(""); leaveType = "casual"; leaveStart = new Date().toISOString().slice(0, 10); leaveEnd = new Date().toISOString().slice(0, 10); leaveReason = ""; constructor(readonly staff: StaffAppService) {} ngOnInit() { if (this.staff.hasPermission("read:staff")) void this.load(); } async load() { this.loading.set(true); try { const [leaves, balances] = await Promise.all([this.staff.leaves(), this.staff.leaveBalances()]); this.leaves.set(leaves); this.balances.set(balances); } finally { this.loading.set(false); } } leaveBalanceValue(balance: StaffLeaveBalance): number { return Number(balance.balance ?? (Number(balance.openingBalance || 0) + Number(balance.accrued || 0) - Number(balance.used || 0))); } async requestLeave() { await this.staff.requestLeave({ leaveType: this.leaveType, startDate: this.leaveStart, endDate: this.leaveEnd, reason: this.leaveReason }).then(() => { this.leaveReason = ""; this.message.set("Leave request sent."); return this.load(); }); } }
