import { CurrencyPipe, DatePipe } from "@angular/common";
import { Component, OnInit, signal } from "@angular/core";
import { IonSpinner } from "@ionic/angular/standalone";
import { StaffAppService, StaffDashboard, StaffEnterpriseOs } from "../../core/staff-app.service";

@Component({ standalone: true, imports: [CurrencyPipe, DatePipe, IonSpinner], template: `
  <section class="page"><header class="page-head"><div><p class="eyebrow">Reports</p><h1>Staff reports</h1><p>Daily, weekly, monthly and yearly staff report view.</p></div></header>
  @if (loading()) { <section class="state"><ion-spinner name="crescent" /> Loading reports...</section> } @if (staff.error()) { <section class="notice">{{ staff.error() }}</section> }
  @if (os(); as data) { <section class="grid four">@for (key of reportKeys(); track key) { <article class="kpi"><span>{{ key }}</span><strong>{{ data.reports[key].services }}</strong><small>{{ data.reports[key].productivityScore }}/100 score</small></article> }</section> }
  @if (dashboard(); as dash) { <section class="grid two"><article class="panel"><div class="panel-title"><h2>Work report</h2><span>{{ dash.workReport.length }}</span></div><div class="list">@for (item of dash.workReport.slice(0, 12); track item.id) { <div class="row"><div class="row-main"><strong>{{ item.clientName || 'Client' }}</strong><small>{{ item.startAt | date:'mediumDate' }} · {{ item.serviceNames.join(', ') || 'Service' }}</small></div><span class="badge">{{ item.status }}</span></div> } @empty { <p class="empty">No completed work in this report window.</p> }</div></article><article class="panel"><div class="panel-title"><h2>Sales</h2><span>{{ dash.sales.length }}</span></div><div class="list">@for (sale of dash.sales.slice(0, 12); track sale.id) { <div class="row"><div class="row-main"><strong>{{ sale.total | currency:'INR':'symbol':'1.0-0' }}</strong><small>{{ sale.createdAt | date:'short' }}</small></div><span class="badge">{{ sale.status }}</span></div> } @empty { <p class="empty">No sales entries visible.</p> }</div></article></section> }
  </section>`, styleUrls: ["./staff-app.styles.css"] })
export class StaffReportsPage implements OnInit { readonly os = signal<StaffEnterpriseOs | null>(null); readonly dashboard = signal<StaffDashboard | null>(null); readonly loading = signal(false); constructor(readonly staff: StaffAppService) {} ngOnInit() { void this.load(); } async load() { this.loading.set(true); try { const [os, dashboard] = await Promise.all([this.staff.enterpriseOs(), this.staff.dashboard()]); this.os.set(os); this.dashboard.set(dashboard); } finally { this.loading.set(false); } } reportKeys(): Array<"daily" | "weekly" | "monthly" | "yearly"> { return ["daily", "weekly", "monthly", "yearly"]; } }
