import { DatePipe } from "@angular/common";
import { Component, OnInit, signal } from "@angular/core";
import { IonSpinner } from "@ionic/angular/standalone";
import { StaffAppService, StaffEnterpriseOs } from "../../core/staff-app.service";

@Component({ standalone: true, imports: [DatePipe, IonSpinner], template: `
  <section class="page"><header class="page-head"><div><p class="eyebrow">Chat</p><h1>Team chat</h1><p>Dedicated communication workspace for staff updates.</p></div><div class="row-actions"><button class="link-button" [class.active-toggle]="filter() === 'all'" type="button" (click)="filter.set('all')">All</button><button class="link-button" [class.active-toggle]="filter() === 'unread'" type="button" (click)="filter.set('unread')">Unread</button><button class="link-button" [class.active-toggle]="filter() === 'system'" type="button" (click)="filter.set('system')">System</button></div></header>
  @if (loading()) { <section class="state"><ion-spinner name="crescent" /> Loading chat workspace...</section> } @if (staff.error()) { <section class="notice">{{ staff.error() }}</section> }
  @if (os(); as data) { <section class="grid two"><article class="panel"><div class="panel-title"><h2>Team thread</h2><span>{{ filteredNotifications().length }}</span></div><div class="list">@for (note of filteredNotifications(); track note.id) { <div class="row"><div class="row-main"><strong>{{ note.title }}</strong><small>{{ note.createdAt ? (note.createdAt | date:'short') : '' }} · {{ note.body || note.status }}</small></div><span class="badge">{{ note.status }}</span></div> } @empty { <p class="empty">No connected chat threads for this filter.</p> }</div></article><article class="panel"><div class="panel-title"><h2>Branch channel</h2><span>{{ staff.user()?.branchId || 'staff' }}</span></div><p class="insight">Realtime branch chat can attach here. Current thread is seeded from staff notifications and AI operational updates.</p>@for (card of data.aiCoach.slice(0, 3); track card.title) { <p class="insight"><b>{{ card.title }}</b>: {{ card.action }}</p> }</article></section> }
  </section>`, styleUrls: ["./staff-app.styles.css"] })
export class StaffChatPage implements OnInit { readonly os = signal<StaffEnterpriseOs | null>(null); readonly loading = signal(false); readonly filter = signal<"all" | "unread" | "system">("all"); constructor(readonly staff: StaffAppService) {} ngOnInit() { void this.load(); } async load() { this.loading.set(true); try { this.os.set(await this.staff.enterpriseOs()); } finally { this.loading.set(false); } } filteredNotifications() { const notes = this.os()?.notifications || []; if (this.filter() === "unread") return notes.filter((note) => String(note.status || "unread") !== "read"); if (this.filter() === "system") return notes.filter((note) => /system|staff|notification/i.test(`${note.title} ${note.body}`)); return notes; } }
