import { Routes } from '@angular/router';

export const MERGED_OPS_ROUTES: Routes = [
  { path: 'leads/follow-up', loadComponent: () => import('../../pages/lead-management-command-center.component').then(m => m.LeadManagementCommandCenterComponent), title: 'Lead Follow Up' },
  { path: 'leads/settings', loadComponent: () => import('../../pages/lead-management-command-center.component').then(m => m.LeadManagementCommandCenterComponent), title: 'Lead Settings' },
  { path: 'leads/:id', loadComponent: () => import('../../pages/lead-management-command-center.component').then(m => m.LeadManagementCommandCenterComponent), title: 'Lead Detail' },
  { path: 'leads', loadComponent: () => import('../../pages/lead-management-command-center.component').then(m => m.LeadManagementCommandCenterComponent), title: 'Lead Management' },
  { path: 'sales-tools', loadComponent: () => import('../../pages/sales-tools-command-center.component').then(m => m.SalesToolsCommandCenterComponent), title: 'Sales Tools Command Center' },
  { path: 'transactions/petty-cash', loadComponent: () => import('../../pages/petty-cash-entry.component').then(m => m.PettyCashEntryComponent), title: 'Petty Cash Entry' },
  { path: 'transactions/petty-cash-report', loadComponent: () => import('../../pages/petty-cash-report.component').then(m => m.PettyCashReportComponent), title: 'Petty Cash Report' },
  { path: 'pos/payment-mode-report', loadComponent: () => import('../../pages/payment-mode-report.component').then(m => m.PaymentModeReportComponent), title: 'Payment Mode Report' },
  { path: 'inventory/purchase-bill-entry', loadComponent: () => import('../../pages/purchase-bill-entry.component').then(m => m.PurchaseBillEntryComponent), title: 'Purchase Bill Entry' },
  { path: 'inventory/purchase-bills', loadComponent: () => import('../../pages/purchase-bill-register.component').then(m => m.PurchaseBillRegisterComponent), title: 'Purchase Bills' },
  { path: 'inventory/purchase-bill-register', loadComponent: () => import('../../pages/purchase-bill-register.component').then(m => m.PurchaseBillRegisterComponent), title: 'Purchase Bill Register' },
  { path: 'setting/bill-setting', loadComponent: () => import('../../pages/bill-settings.component').then(m => m.BillSettingsComponent), title: 'Bill Settings' },
  { path: 'settings/bill-setting', loadComponent: () => import('../../pages/bill-settings.component').then(m => m.BillSettingsComponent), title: 'Bill Settings' },
  { path: 'settings/booking', loadComponent: () => import('../../pages/booking-settings.component').then(m => m.BookingSettingsComponent), title: 'Booking Settings' },
  { path: 'settings/business-details', loadComponent: () => import('../../pages/business-details-settings.component').then(m => m.BusinessDetailsSettingsComponent), title: 'Business Details Settings' },
  { path: 'settings/consent-forms', loadComponent: () => import('../../pages/consent-forms-settings.component').then(m => m.ConsentFormsSettingsComponent), title: 'Consent Forms Settings' },
  { path: 'settings/custom-fields', loadComponent: () => import('../../pages/custom-fields-settings.component').then(m => m.CustomFieldsSettingsComponent), title: 'Custom Fields Settings' },
  { path: 'settings/general', loadComponent: () => import('../../pages/general-settings.component').then(m => m.GeneralSettingsComponent), title: 'General Settings' },
  { path: 'settings/inventory', loadComponent: () => import('../../pages/inventory-settings.component').then(m => m.InventorySettingsComponent), title: 'Inventory Settings' },
  { path: 'settings/membership', loadComponent: () => import('../../pages/membership-settings.component').then(m => m.MembershipSettingsComponent), title: 'Membership Settings' },
  { path: 'settings/message-history', loadComponent: () => import('../../pages/message-history-settings.component').then(m => m.MessageHistorySettingsComponent), title: 'Message History Settings' },
  { path: 'settings/multiple-location', loadComponent: () => import('../../pages/multiple-location-settings.component').then(m => m.MultipleLocationSettingsComponent), title: 'Multiple Location Settings' },
  { path: 'settings/others', loadComponent: () => import('../../pages/other-settings.component').then(m => m.OtherSettingsComponent), title: 'Other Settings' },
  { path: 'settings/packages', loadComponent: () => import('../../pages/package-settings.component').then(m => m.PackageSettingsComponent), title: 'Packages Settings' },
  { path: 'settings/payment-methods', loadComponent: () => import('../../pages/payment-method-settings.component').then(m => m.PaymentMethodSettingsComponent), title: 'Payment Methods Settings' },
  { path: 'settings/products', loadComponent: () => import('../../pages/product-settings.component').then(m => m.ProductSettingsComponent), title: 'Products Settings' },
  { path: 'mfa-security', loadComponent: () => import('../../pages/security-mfa.component').then(m => m.SecurityMfaComponent), title: 'MFA Security' },
  { path: 'passkeys', loadComponent: () => import('../../pages/passkeys.component').then(m => m.PasskeysComponent), title: 'Passkeys' },
  { path: 'settings/mfa-security', loadComponent: () => import('../../pages/security-mfa.component').then(m => m.SecurityMfaComponent), title: 'MFA Security' },
  { path: 'settings/passkeys', loadComponent: () => import('../../pages/passkeys.component').then(m => m.PasskeysComponent), title: 'Passkeys' },
  { path: 'settings/security', loadComponent: () => import('../../pages/security-settings.component').then(m => m.SecuritySettingsComponent), title: 'Security Settings' },
  { path: 'settings/services', loadComponent: () => import('../../pages/service-settings.component').then(m => m.ServiceSettingsComponent), title: 'Services Settings' },
  { path: 'settings/sms-template', loadComponent: () => import('../../pages/sms-template-settings.component').then(m => m.SmsTemplateSettingsComponent), title: 'SMS Template Settings' },
  { path: 'settings/supplier', loadComponent: () => import('../../pages/supplier-settings.component').then(m => m.SupplierSettingsComponent), title: 'Supplier Settings' },
  { path: 'inventory/laundry-entry', loadComponent: () => import('../../pages/laundry-entry.component').then(m => m.LaundryEntryComponent), title: 'Laundry Inward / Outward' },
  { path: 'inventory/laundry-report', loadComponent: () => import('../../pages/laundry-report.component').then(m => m.LaundryReportComponent), title: 'Laundry Entries Report' }
];
