import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const depositGateService = readFileSync("server/services/appointment-deposit-gate.service.js", "utf8");
const auditRoutes = readFileSync("server/routes/audit.routes.js", "utf8");
const appointmentDepositRoutes = readFileSync("server/routes/appointment-deposit-gate.routes.js", "utf8");
const appComponent = readFileSync("src/app/app.component.ts", "utf8");
const appointmentEnterprisePage = readFileSync("src/app/pages/appointments-enterprise.component.ts", "utf8");
const depositReportPage = readFileSync("src/app/pages/appointment-deposit-report.component.ts", "utf8");
const invoiceActivityPage = readFileSync("src/app/pages/pos-invoice-activity.component.ts", "utf8");

test("deposit report and invoice activity expose settlement breakdown columns", () => {
  assert.match(appComponent, /depositAdjustedDueCount = signal\(0\)/, "App shell should keep a sidebar count for adjusted plus due deposits");
  assert.match(appComponent, /item\.path === '\/appointment-deposits'/, "Sidebar badge should attach to the deposit report nav item");
  assert.match(appComponent, /appointment-deposits\/report/, "Sidebar count should load from the deposit report API");
  assert.match(appComponent, /advanceAdjusted \|\| 0\) > 0 && Number\(row\.counterDue \|\| 0\) > 0/, "Sidebar count should reflect adjusted plus due bookings only");
  assert.match(appComponent, /adjusted plus due booking\(s\) need front desk follow-up/, "Sidebar badge title should explain the follow-up queue");
  assert.match(appointmentEnterprisePage, /Front-desk follow-up/, "Appointments header should surface the follow-up alert strip");
  assert.match(appointmentEnterprisePage, /adjustedDueFollowUpCount = signal\(0\)/, "Appointments page should track adjusted plus due follow-up count");
  assert.match(appointmentEnterprisePage, /appointment-deposits\/report/, "Appointments page should reuse the deposit report API for follow-up truth");
  assert.match(appointmentEnterprisePage, /Open deposit report/, "Appointments header should include a CTA to the deposit report");
  assert.match(appointmentEnterprisePage, /this\.router\.navigateByUrl\('\/appointment-deposits\?settlement=adjusted_due'\)/, "Appointments CTA should deep-link into adjusted plus due deposit report mode");
  assert.match(appointmentEnterprisePage, /queryParamMap\.get\('appointmentId'\)/, "Appointments page should accept appointment deep-links");
  assert.match(appointmentEnterprisePage, /this\.openAppointment\(appointment\)/, "Appointments page should open the routed appointment drawer");
  assert.match(depositReportPage, /Advance adjusted/, "Deposit report page should show advance adjusted column");
  assert.match(depositReportPage, /Counter paid/, "Deposit report page should show counter paid column");
  assert.match(depositReportPage, /Counter due/, "Deposit report page should show counter due column");
  assert.match(depositReportPage, /Adjusted \+ due/, "Deposit report page should expose adjusted plus due settlement filter");
  assert.match(depositReportPage, /queryParamMap\.get\('settlement'\)/, "Deposit report page should read settlement deep-link query params");
  assert.match(depositReportPage, /settlementFilterFromQuery/, "Deposit report page should normalize deep-link settlement filters");
  assert.match(depositReportPage, /Open invoice/, "Deposit report rows should include invoice actions");
  assert.match(depositReportPage, /Open appointment/, "Deposit report rows should include appointment actions");
  assert.match(depositReportPage, /Send reminder/, "Deposit report rows should include payment reminder actions");
  assert.match(depositReportPage, /Mark done/, "Deposit report rows should let staff close follow-up");
  assert.match(depositReportPage, /payments\/invoices\/\$\{invoiceId\}\/reminder/, "Deposit report reminder action should reuse invoice reminder API");
  assert.match(depositReportPage, /appointment-deposits\/followups\/\$\{row\.paymentLinkId\}/, "Deposit report follow-up actions should persist status updates");
  assert.match(depositReportPage, /Follow-up pending \{\{ adjustedDuePendingCount\(\) \}\}/, "Deposit report page should offer a one-click follow-up action");
  assert.match(depositReportPage, /focusAdjustedDueFollowUp\(\)/, "Follow-up action should jump straight into adjusted plus due mode");
  assert.match(depositReportPage, /exportCsv\(\)/, "Deposit report page should export the filtered settlement rows to CSV");
  assert.match(depositReportPage, /exportPdf\(\)/, "Deposit report page should export the filtered settlement rows to PDF");
  assert.match(depositReportPage, /if \(filter === 'adjusted_due'\) return advanceAdjusted > 0 && counterDue > 0;/, "Deposit report should let staff isolate adjusted bookings that still have counter due");
  assert.match(depositReportPage, /rowFollowUpStatus\(row\)/, "Deposit report page should render live follow-up status");
  assert.match(appointmentDepositRoutes, /\/appointment-deposits\/followups\/:paymentLinkId/, "Deposit routes should expose follow-up persistence API");
  assert.match(depositGateService, /SELECT \* FROM invoices WHERE tenant_id = \? AND appointment_id IN/, "Deposit report should look up appointment-linked invoices");
  assert.match(depositGateService, /SELECT \* FROM invoice_payments WHERE tenant_id = \? AND invoice_id IN/, "Deposit report should look up paid invoice payment rows");
  assert.match(depositGateService, /advanceAdjusted:\s*bookingAdvanceAdjustedAmount\(payments\)/, "Deposit report should derive adjusted advance from booking advance payments");
  assert.match(depositGateService, /counterPaid:\s*counterPaymentCollectedAmount\(invoice,\s*payments\)/, "Deposit report should derive counter paid from invoice settlement");
  assert.match(depositGateService, /counterDue:\s*counterPaymentDueAmount\(invoice\)/, "Deposit report should derive remaining counter due from invoice balance");
  assert.match(depositGateService, /appointment_deposit_followups/, "Deposit report backend should persist follow-up rows");
  assert.match(depositGateService, /followUpStatus/, "Deposit report backend should expose follow-up status to the UI");

  assert.match(invoiceActivityPage, /Advance adjusted/, "Invoice activity page should show advance adjusted columns");
  assert.match(invoiceActivityPage, /Counter paid/, "Invoice activity page should show counter paid columns");
  assert.match(invoiceActivityPage, /booking_advance:\s*'Booking advance'/, "Invoice activity page should humanize booking advance payment mode");
  assert.match(auditRoutes, /advanceAdjusted:\s*bookingAdvanceAdjustedAmount\(merged\)/, "Invoice activity API should expose advance adjusted truth");
  assert.match(auditRoutes, /counterPaid:\s*counterPaymentCollectedAmount\(merged\)/, "Invoice activity API should expose counter paid truth");
  assert.match(auditRoutes, /"advanceAdjusted"/, "Invoice activity CSV export should keep advance adjusted column");
  assert.match(auditRoutes, /"counterPaid"/, "Invoice activity CSV export should keep counter paid column");
});
