CREATE TABLE IF NOT EXISTS legacy_revenue_imports (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  branch_id TEXT DEFAULT '',
  source_system TEXT DEFAULT 'FlexiSalonERP',
  file_name TEXT DEFAULT '',
  report_title TEXT DEFAULT '',
  report_from TEXT DEFAULT '',
  report_to TEXT DEFAULT '',
  data_from TEXT DEFAULT '',
  data_to TEXT DEFAULT '',
  row_count INTEGER DEFAULT 0,
  invoice_count INTEGER DEFAULT 0,
  line_count INTEGER DEFAULT 0,
  total_amount REAL DEFAULT 0,
  received_amount REAL DEFAULT 0,
  unpaid_amount REAL DEFAULT 0,
  balance_paid_amount REAL DEFAULT 0,
  cash_amount REAL DEFAULT 0,
  card_amount REAL DEFAULT 0,
  online_amount REAL DEFAULT 0,
  cheque_amount REAL DEFAULT 0,
  tip_amount REAL DEFAULT 0,
  summary_json TEXT DEFAULT '{}',
  imported_by TEXT DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS legacy_revenue_invoices (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  branch_id TEXT DEFAULT '',
  import_id TEXT NOT NULL,
  source_branch TEXT DEFAULT '',
  doc_type TEXT DEFAULT '',
  doc_date TEXT DEFAULT '',
  invoice_no TEXT NOT NULL,
  client_branch TEXT DEFAULT '',
  membership TEXT DEFAULT '',
  membership_no TEXT DEFAULT '',
  client_name TEXT DEFAULT '',
  mobile_no TEXT DEFAULT '',
  person TEXT DEFAULT '',
  gstin TEXT DEFAULT '',
  gender TEXT DEFAULT '',
  home_service TEXT DEFAULT '',
  line_count INTEGER DEFAULT 0,
  amount REAL DEFAULT 0,
  discount_amount REAL DEFAULT 0,
  total_deduction REAL DEFAULT 0,
  taxable_amount REAL DEFAULT 0,
  cgst_amount REAL DEFAULT 0,
  sgst_amount REAL DEFAULT 0,
  total_gst_amount REAL DEFAULT 0,
  net_amount REAL DEFAULT 0,
  round_off_amount REAL DEFAULT 0,
  total_amount REAL DEFAULT 0,
  previous_balance_amount REAL DEFAULT 0,
  advance_amount REAL DEFAULT 0,
  total_due_amount REAL DEFAULT 0,
  total_business_amount REAL DEFAULT 0,
  received_amount REAL DEFAULT 0,
  cash_amount REAL DEFAULT 0,
  card_amount REAL DEFAULT 0,
  online_amount REAL DEFAULT 0,
  cheque_amount REAL DEFAULT 0,
  ewallet_name TEXT DEFAULT '',
  unpaid_amount REAL DEFAULT 0,
  balance_paid_amount REAL DEFAULT 0,
  prepared_by TEXT DEFAULT '',
  remarks TEXT DEFAULT '',
  tip_amount REAL DEFAULT 0,
  raw_json TEXT DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(tenant_id, import_id, invoice_no)
);

CREATE TABLE IF NOT EXISTS legacy_revenue_lines (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  branch_id TEXT DEFAULT '',
  import_id TEXT NOT NULL,
  invoice_id TEXT NOT NULL,
  source_branch TEXT DEFAULT '',
  doc_type TEXT DEFAULT '',
  doc_date TEXT DEFAULT '',
  invoice_no TEXT NOT NULL,
  line_no INTEGER DEFAULT 0,
  service_product TEXT DEFAULT '',
  operator TEXT DEFAULT '',
  assistant_operator TEXT DEFAULT '',
  quantity REAL DEFAULT 0,
  discount_percent REAL DEFAULT 0,
  discount_amount REAL DEFAULT 0,
  item_amount REAL DEFAULT 0,
  invoice_amount REAL DEFAULT 0,
  free_amount REAL DEFAULT 0,
  gift_amount REAL DEFAULT 0,
  deducted_discount_percent REAL DEFAULT 0,
  deducted_discount_amount REAL DEFAULT 0,
  non_deducted_discount_percent REAL DEFAULT 0,
  non_deducted_discount_amount REAL DEFAULT 0,
  scheme_discount_percent REAL DEFAULT 0,
  scheme_discount_amount REAL DEFAULT 0,
  total_deduction REAL DEFAULT 0,
  taxable_amount REAL DEFAULT 0,
  tax_code TEXT DEFAULT '',
  cgst_amount REAL DEFAULT 0,
  sgst_amount REAL DEFAULT 0,
  total_gst_amount REAL DEFAULT 0,
  net_amount REAL DEFAULT 0,
  total_amount REAL DEFAULT 0,
  total_business_amount REAL DEFAULT 0,
  received_amount REAL DEFAULT 0,
  unpaid_amount REAL DEFAULT 0,
  balance_paid_amount REAL DEFAULT 0,
  raw_json TEXT DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_legacy_revenue_imports_scope ON legacy_revenue_imports(tenant_id, branch_id, created_at);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_invoices_scope_date ON legacy_revenue_invoices(tenant_id, branch_id, doc_date);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_invoices_import ON legacy_revenue_invoices(tenant_id, import_id);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_invoices_no ON legacy_revenue_invoices(tenant_id, invoice_no);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_lines_invoice ON legacy_revenue_lines(tenant_id, invoice_id);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_lines_import ON legacy_revenue_lines(tenant_id, import_id);
CREATE INDEX IF NOT EXISTS idx_legacy_revenue_lines_operator ON legacy_revenue_lines(tenant_id, operator);
