import { Router } from "express";
import { staffMasterService } from "../services/staff-master.service.js";
import { staffLoginService } from "../services/staff-login.service.js";
import { route } from "./staff-os-route-utils.js";

export const staffMasterRouter = Router();

staffMasterRouter.get("/staff-os/staff-categories", route((req, res) => res.json(staffMasterService.listStaffCategories(req.query, req.access))));
staffMasterRouter.post("/staff-os/staff-categories", route((req, res) => res.status(201).json(staffMasterService.createStaffCategory(req.body, req.access))));
staffMasterRouter.get("/staff-os/staff-categories/:id", route((req, res) => res.json(staffMasterService.getStaffCategory(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/staff-categories/:id", route((req, res) => res.json(staffMasterService.updateStaffCategory(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/staff-categories/:id/status", route((req, res) => res.json(staffMasterService.updateStaffCategoryStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/attendance-masters", route((req, res) => res.json(staffMasterService.listAttendanceStatusMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/attendance-masters", route((req, res) => res.status(201).json(staffMasterService.createAttendanceStatusMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/attendance-masters/:id", route((req, res) => res.json(staffMasterService.getAttendanceStatusMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/attendance-masters/:id", route((req, res) => res.json(staffMasterService.updateAttendanceStatusMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/attendance-masters/:id/status", route((req, res) => res.json(staffMasterService.updateAttendanceStatusMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/leave-masters", route((req, res) => res.json(staffMasterService.listLeaveTypeMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/leave-masters", route((req, res) => res.status(201).json(staffMasterService.createLeaveTypeMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/leave-masters/:id", route((req, res) => res.json(staffMasterService.getLeaveTypeMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/leave-masters/:id", route((req, res) => res.json(staffMasterService.updateLeaveTypeMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/leave-masters/:id/status", route((req, res) => res.json(staffMasterService.updateLeaveTypeMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/shift-masters", route((req, res) => res.json(staffMasterService.listShiftTemplates(req.query, req.access))));
staffMasterRouter.post("/staff-os/shift-masters", route((req, res) => res.status(201).json(staffMasterService.createShiftTemplate(req.body, req.access))));
staffMasterRouter.get("/staff-os/shift-masters/:id", route((req, res) => res.json(staffMasterService.getShiftTemplate(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/shift-masters/:id", route((req, res) => res.json(staffMasterService.updateShiftTemplate(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/shift-masters/:id/status", route((req, res) => res.json(staffMasterService.updateShiftTemplateStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/attendance-categories", route((req, res) => res.json(staffMasterService.listAttendanceCategoryMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/attendance-categories", route((req, res) => res.status(201).json(staffMasterService.createAttendanceCategoryMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/attendance-categories/:id", route((req, res) => res.json(staffMasterService.getAttendanceCategoryMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/attendance-categories/:id", route((req, res) => res.json(staffMasterService.updateAttendanceCategoryMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/attendance-categories/:id/status", route((req, res) => res.json(staffMasterService.updateAttendanceCategoryMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/target-incentives", route((req, res) => res.json(staffMasterService.listTargetIncentiveMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/target-incentives", route((req, res) => res.status(201).json(staffMasterService.createTargetIncentiveMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/target-incentives/:id", route((req, res) => res.json(staffMasterService.getTargetIncentiveMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/target-incentives/:id", route((req, res) => res.json(staffMasterService.updateTargetIncentiveMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/target-incentives/:id/status", route((req, res) => res.json(staffMasterService.updateTargetIncentiveMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.post("/staff-os/target-incentives/:id/copy", route((req, res) => res.json(staffMasterService.copyTargetIncentiveMaster(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/service-assignments", route((req, res) => res.json(staffMasterService.listServiceAssignmentMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/service-assignments", route((req, res) => res.status(201).json(staffMasterService.createServiceAssignmentMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/service-assignments/:id", route((req, res) => res.json(staffMasterService.getServiceAssignmentMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/service-assignments/:id", route((req, res) => res.json(staffMasterService.updateServiceAssignmentMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/service-assignments/:id/status", route((req, res) => res.json(staffMasterService.updateServiceAssignmentMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.post("/staff-os/service-assignments/:id/copy", route((req, res) => res.json(staffMasterService.copyServiceAssignmentMaster(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/fine-penalties", route((req, res) => res.json(staffMasterService.listFinePenaltyMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/fine-penalties", route((req, res) => res.status(201).json(staffMasterService.createFinePenaltyMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/fine-penalties/:id", route((req, res) => res.json(staffMasterService.getFinePenaltyMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/fine-penalties/:id", route((req, res) => res.json(staffMasterService.updateFinePenaltyMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/fine-penalties/:id/status", route((req, res) => res.json(staffMasterService.updateFinePenaltyMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/allowance-deductions", route((req, res) => res.json(staffMasterService.listAllowanceDeductionMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/allowance-deductions", route((req, res) => res.status(201).json(staffMasterService.createAllowanceDeductionMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/allowance-deductions/:id", route((req, res) => res.json(staffMasterService.getAllowanceDeductionMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/allowance-deductions/:id", route((req, res) => res.json(staffMasterService.updateAllowanceDeductionMaster(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/allowance-deductions/:id/status", route((req, res) => res.json(staffMasterService.updateAllowanceDeductionMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/payroll-structures", route((req, res) => res.json(staffMasterService.listPayrollSalaryStructureMasters(req.query, req.access))));
staffMasterRouter.post("/staff-os/payroll-structures", route((req, res) => res.status(201).json(staffMasterService.upsertPayrollSalaryStructureMaster(req.body, req.access))));
staffMasterRouter.get("/staff-os/payroll-structures/:id", route((req, res) => res.json(staffMasterService.getPayrollSalaryStructureMaster(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/payroll-structures/:id", route((req, res) => res.json(staffMasterService.upsertPayrollSalaryStructureMaster({ ...req.body, id: req.params.id }, req.access))));
staffMasterRouter.patch("/staff-os/payroll-structures/:id/status", route((req, res) => res.json(staffMasterService.updatePayrollSalaryStructureMasterStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/bulk-employee-update", route((req, res) => res.json(staffMasterService.listBulkEmployeeUpdateRows(req.query, req.access))));
staffMasterRouter.post("/staff-os/bulk-employee-update", route((req, res) => res.json(staffMasterService.applyBulkEmployeeUpdate(req.body, req.access))));
staffMasterRouter.get("/staff-os/staff", route((req, res) => res.json(staffMasterService.listStaff(req.query, req.access))));
staffMasterRouter.post("/staff-os/staff", route((req, res) => res.status(201).json(staffMasterService.createStaff(req.body, req.access))));
staffMasterRouter.post("/staff-os/staff/media", route((req, res) => {
  const publicBaseUrl = `${req.protocol}://${req.get("host")}`;
  res.status(201).json(staffMasterService.uploadStaffPhoto(req.body, req.access, { publicBaseUrl }));
}));
staffMasterRouter.get("/staff-os/staff/:id", route((req, res) => res.json(staffMasterService.getStaff(req.params.id, req.access))));
staffMasterRouter.patch("/staff-os/staff/:id", route((req, res) => res.json(staffMasterService.updateStaff(req.params.id, req.body, req.access))));
staffMasterRouter.patch("/staff-os/staff/:id/status", route((req, res) => res.json(staffMasterService.updateStaffStatus(req.params.id, req.body, req.access))));
staffMasterRouter.get("/staff-os/staff/:id/login", route((req, res) => res.json(staffLoginService.getStaffLogin(req.params.id, req.access))));
staffMasterRouter.post("/staff-os/staff/:id/login", route((req, res) => res.json(staffLoginService.upsertStaffLogin(req.params.id, req.body, req.access))));
staffMasterRouter.post("/staff-os/staff/:id/documents", route((req, res) => res.status(201).json(staffMasterService.addStaffDocument(req.params.id, req.body, req.access))));
staffMasterRouter.post("/staff-os/staff/:id/skills", route((req, res) => res.status(201).json(staffMasterService.addStaffSkill(req.params.id, req.body, req.access))));
