import { Router } from "express";
import { staffApprovalRouter } from "./staff-approval.routes.js";
import { staffAttendanceRouter } from "./staff-attendance.routes.js";
import { staffAuditRouter } from "./staff-audit.routes.js";
import { staffBiometricRouter } from "./staff-biometric.routes.js";
import { staffCommissionRouter } from "./staff-commission.routes.js";
import { staffIntelligenceRouter } from "./staff-intelligence.routes.js";
import { staffLeaveRouter } from "./staff-leave.routes.js";
import { staffManpowerForecastRouter } from "./staff-manpower-forecast.routes.js";
import { staffMasterRouter } from "./staff-master.routes.js";
import { staffMobileRouter } from "./staff-mobile.routes.js";
import { staffMobileSyncRouter } from "./staff-mobile-sync.routes.js";
import { staffPayrollRouter } from "./staff-payroll.routes.js";
import { staffPayrollComplianceRouter } from "./staff-payroll-compliance.routes.js";
import { staffPerformanceRouter } from "./staff-performance.routes.js";
import { staffReplacementEngineRouter } from "./staff-replacement-engine.routes.js";
import { staffReportsRouter } from "./staff-reports.routes.js";
import { staffRosterOptimizerRouter } from "./staff-roster-optimizer.routes.js";
import { staffScheduleRouter } from "./staff-schedule.routes.js";
import { staffTaskRouter } from "./staff-task.routes.js";
import { staffTipsRouter } from "./staff-tips.routes.js";
import { staffWhatsappNotificationRouter } from "./staff-whatsapp-notification.routes.js";

export const staffOsRouter = Router();

staffOsRouter.use(staffMasterRouter);
staffOsRouter.use(staffScheduleRouter);
staffOsRouter.use(staffAttendanceRouter);
staffOsRouter.use(staffLeaveRouter);
staffOsRouter.use(staffPayrollRouter);
staffOsRouter.use(staffCommissionRouter);
staffOsRouter.use(staffTipsRouter);
staffOsRouter.use(staffPerformanceRouter);
staffOsRouter.use(staffIntelligenceRouter);
staffOsRouter.use(staffMobileRouter);
staffOsRouter.use(staffTaskRouter);
staffOsRouter.use(staffAuditRouter);
staffOsRouter.use(staffReportsRouter);
staffOsRouter.use(staffBiometricRouter);
staffOsRouter.use(staffWhatsappNotificationRouter);
staffOsRouter.use(staffPayrollComplianceRouter);
staffOsRouter.use(staffReplacementEngineRouter);
staffOsRouter.use(staffMobileSyncRouter);
staffOsRouter.use(staffApprovalRouter);
staffOsRouter.use(staffRosterOptimizerRouter);
staffOsRouter.use(staffManpowerForecastRouter);
