export const aiTasks = {
  "review.reply": { tier: "smart", cacheable: true, ttl: 86400 },
  "chatbot.conversation": { tier: "smart", cacheable: false },
  "marketing.caption": { tier: "smart", cacheable: true, ttl: 3600 },
  "analytics.summary": { tier: "smart", cacheable: true, ttl: 1800 },
  "churn.explanation": { tier: "smart", cacheable: true, ttl: 21600 },
  "upsell.recommendation": { tier: "fast", cacheable: false },
  "customer360.health_score": { tier: "fast", cacheable: true, ttl: 1800 },
  "customer360.churn_risk": { tier: "fast", cacheable: true, ttl: 1800 },
  "customer360.next_best_action": { tier: "fast", cacheable: true, ttl: 1800 },
  "customer360.upsell_recommendation": { tier: "fast", cacheable: true, ttl: 1800 },
  "customer360.rebooking_recommendation": { tier: "fast", cacheable: true, ttl: 1800 },
  "calendar.smart_slot_score": { tier: "fast", cacheable: true, ttl: 600 },
  "calendar.no_show_risk": { tier: "fast", cacheable: true, ttl: 900 },
  "calendar.conflict_doctor": { tier: "fast", cacheable: false },
  "calendar.revenue_gap_filler": { tier: "fast", cacheable: true, ttl: 900 },
  "calendar.staff_load_signal": { tier: "fast", cacheable: true, ttl: 900 },
  "calendar.delay_prediction": { tier: "fast", cacheable: true, ttl: 600 },
  "calendar.booking_quality_score": { tier: "fast", cacheable: true, ttl: 900 },
  "pos.smart_upsell": { tier: "fast", cacheable: true, ttl: 600 },
  "pos.membership_suggestion": { tier: "fast", cacheable: true, ttl: 900 },
  "pos.discount_guard": { tier: "fast", cacheable: false },
  "pos.payment_recovery": { tier: "fast", cacheable: true, ttl: 900 },
  "pos.cart_profitability": { tier: "fast", cacheable: false },
  "inventory.reorder_prediction": { tier: "fast", cacheable: true, ttl: 1800 },
  "inventory.expiry_waste_risk": { tier: "fast", cacheable: true, ttl: 1800 },
  "inventory.service_stock_readiness": { tier: "fast", cacheable: true, ttl: 900 },
  "inventory.low_stock_reason": { tier: "fast", cacheable: true, ttl: 1800 },
  "inventory.purchase_plan": { tier: "fast", cacheable: true, ttl: 1800 },
  "whatsapp.intent_detection": { tier: "fast", cacheable: true, ttl: 300 },
  "whatsapp.reply_generation": { tier: "smart", cacheable: false },
  "whatsapp.followup_draft": { tier: "fast", cacheable: true, ttl: 900 },
  "whatsapp.rebooking_draft": { tier: "fast", cacheable: true, ttl: 900 },
  "whatsapp.payment_reminder_draft": { tier: "fast", cacheable: true, ttl: 900 },
  "dashboard.executive_summary": { tier: "fast", cacheable: true, ttl: 900 },
  "dashboard.risk_briefing": { tier: "fast", cacheable: true, ttl: 900 },
  "dashboard.revenue_actions": { tier: "fast", cacheable: true, ttl: 900 },
  "dashboard.owner_daily_brief": { tier: "smart", cacheable: true, ttl: 900 },
  "whatsapp.agent_triage": { tier: "fast", cacheable: false },
  "knowledge.search_summary": { tier: "fast", cacheable: true, ttl: 900 },
  "automation.suggestion": { tier: "fast", cacheable: false },
  "prediction.client_churn": { tier: "fast", cacheable: true, ttl: 1800 },
  "prediction.no_show": { tier: "fast", cacheable: true, ttl: 900 },
  "prediction.demand_forecast": { tier: "fast", cacheable: true, ttl: 1800 },
  "prediction.inventory_stockout": { tier: "fast", cacheable: true, ttl: 1800 },
  "prediction.revenue_leakage": { tier: "fast", cacheable: true, ttl: 900 }
};

export function taskConfig(taskKey) {
  return aiTasks[taskKey] || { tier: "fast", cacheable: false };
}
