import cors from "cors";
import express from "express";
import { existsSync } from "node:fs";
import { join } from "node:path";
import "./db.js";
import { env } from "./config/env.js";
import { initializeDatabaseRuntime } from "./utils/db-init.js";
import { ensureAppointmentSystemSchema } from "./services/appointment-schema.service.js";
import { ensureAppointmentActivitySchema } from "./services/appointment-activity-schema.service.js";
import { ensureEnterpriseSchedulerSchema } from "./services/enterprise-scheduler-schema.service.js";
import { ensureClientMasterSchema } from "./services/client-master-schema.service.js";
import { ensureStaffOsSchema } from "./services/staff-os-schema.service.js";
import { ensureStatutoryComplianceSchema } from "./services/compliance/compliance-schema.service.js";
import { ensureInvoiceNotificationSchema } from "./services/invoice-notification-schema.service.js";
import { ensureReputationSchema } from "./services/reputation/reputation-schema.service.js";
import { ensureAccountMasterSchema } from "./services/account-master-schema.service.js";
import { ensureAccountLedgerSchema } from "./services/account-ledger-schema.service.js";
import { ensureTransactionsSchema } from "./services/transactions-schema.service.js";
import { ensureBalanceSheetSchema } from "./services/balance-sheet-schema.service.js";
import { ensureHardeningSchema } from "./services/balance-sheet-hardening-schema.service.js";
import { ensureAdvancedSchema } from "./services/balance-sheet-advanced-schema.service.js";
import { ensureAiWorkforceOsSchema } from "./services/ai-workforce/ai-workforce-schema.service.js";
import { ensureSupplierCommandSchema } from "./services/supplier-command-schema.service.js";
import { ensureEngagementSchema } from "./services/engagement-schema.service.js";
import { ensurePurchaseBillDraftSchema } from "./services/purchase-bill-schema.service.js";
import { ensureProductUnitSchema } from "./services/inventory-enterprise.service.js";
import { ensureInvoicePaymentCollectionSchema } from "./services/invoice-payment-collection-schema.service.js";
import { ensureGrowthRankBotSchema } from "./services/growth-rank-bot-schema.service.js";
import { ensureLegacyRevenueSchema } from "./services/legacy-revenue-schema.service.js";
import { ensureWaitlistSchema } from "./services/waitlist-schema.service.js";
import { ensureTwoFactorSchema } from "./services/two-factor-schema.service.js";
import { ensureSecurityAlertsSchema } from "./services/security-alerts-schema.service.js";
import { ensureSecurityBlocklistSchema } from "./services/security-blocklist-schema.service.js";
import { ensureSecurityAdvancedSchema } from "./services/security-advanced-schema.service.js";
import { errorHandler, notFoundHandler } from "./middleware/error-handler.js";
import { authenticateJwt } from "./middleware/auth.js";
import { mobileApiContext } from "./middleware/mobile-response.js";
import { requestContext } from "./middleware/request-context.js";
import { enterpriseSecurity } from "./middleware/security.js";
import { securityBlocklistMiddleware } from "./middleware/security-blocklist.middleware.js";
import { securityHeadersPlus } from "./middleware/security-headers-plus.middleware.js";
import { exportProtectionMiddleware } from "./middleware/export-protection.middleware.js";
import { sessionKillSwitchMiddleware } from "./middleware/session-kill-switch.middleware.js";
import { subscriptionGuardMiddleware } from "./middleware/subscription-guard.middleware.js";
import { auditLogMiddleware } from "./middleware/audit-log.middleware.js";
import { idempotencyMiddleware } from "./middleware/idempotency.middleware.js";
import { aiRouter } from "./routes/ai.routes.js";
import { accountMasterRouter } from "./routes/account-master.routes.js";
import { transactionsRouter } from "./routes/transactions.routes.js";
import { balanceSheetRouter } from "./routes/balance-sheet.routes.js";
import { balanceSheetHardeningRouter } from "./routes/balance-sheet-hardening.routes.js";
import { balanceSheetAdvancedRouter } from "./routes/balance-sheet-advanced.routes.js";
import { aiMarketingRouter } from "./routes/ai-marketing.routes.js";
import { growthRankBotRouter } from "./routes/growth-rank-bot.routes.js";
import { analyticsRouter } from "./routes/analytics.routes.js";
import { auditRouter } from "./routes/audit.routes.js";
import { authRouter } from "./routes/auth.routes.js";
import { twoFactorRouter } from "./routes/two-factor.routes.js";
import { securityAlertsRouter } from "./routes/security-alerts.routes.js";
import { securityBlocklistRouter } from "./routes/security-blocklist.routes.js";
import { securityAdvancedRouter } from "./routes/security-advanced.routes.js";
import { securityHoneypotRouter } from "./routes/security-honeypot.routes.js";
import { appointmentSafetyRouter, calendarPublicRouter } from "./routes/appointment-safety.routes.js";
import { appointmentActivityRouter } from "./routes/appointment-activity.routes.js";
import { appointmentSmsRouter } from "./routes/appointment-sms.routes.js";
import { enterpriseSchedulerRouter } from "./routes/enterprise-scheduler.routes.js";
import { billingRouter } from "./routes/billing.routes.js";
import { billingAnalyticsRouter } from "./routes/billing-analytics.routes.js";
import { billingHealthRouter } from "./routes/billing-health.routes.js";
import { bookingPaymentsPublicRouter, bookingPaymentsRouter } from "./routes/booking-payments.routes.js";
import { appointmentDepositGateRouter } from "./routes/appointment-deposit-gate.routes.js";
import { bookingAnalyticsRouter } from "./routes/booking-analytics.routes.js";
import { bookingIntelligenceRouter } from "./routes/booking-intelligence.routes.js";
import { bookingPortalRouter } from "./routes/booking-portal.routes.js";
import { bookingPortalV2Router } from "./routes/booking-portal-v2.routes.js";
import { crmRouter } from "./routes/crm.routes.js";
import { clientMasterRouter } from "./routes/client-master.routes.js";
import { customer360Router } from "./routes/customer-360.routes.js";
import { clientReportsRouter } from "./routes/client-reports.routes.js";
import { dashboardRouter } from "./routes/dashboard.routes.js";
import { commissionRouter } from "./routes/commission.routes.js";
import { statutoryComplianceRouter } from "./routes/compliance.routes.js";
import { corporateBillingRouter } from "./routes/corporate-billing.routes.js";
import { deploymentRouter } from "./routes/deployment.routes.js";
import { discountApprovalRouter } from "./routes/discount-approval.routes.js";
import { ecosystemRouter } from "./routes/ecosystem.routes.js";
import { enterpriseCommandRouter } from "./routes/enterprise-command.routes.js";
import { engagementRouter } from "./routes/engagement.routes.js";
import { financeEngineRouter } from "./routes/finance-engine.routes.js";
import { futureFeaturesRouter } from "./routes/future-features.routes.js";
import { giftCardRouter } from "./routes/gift-card.routes.js";
import { gstRouter } from "./routes/gst.routes.js";
import { invoiceLedgerRouter } from "./routes/invoice-ledger.routes.js";
import { invoiceNotificationRouter } from "./routes/invoice-notification.routes.js";
import { inventoryIntelligenceRouter } from "./routes/inventory-intelligence.routes.js";
import { legacyRevenueRouter } from "./routes/legacy-revenue.routes.js";
import { localizationPreferenceRouter } from "./routes/localization-preference.routes.js";
import { membershipEnterpriseRouter } from "./routes/membership-enterprise.routes.js";
import { migrationRouter } from "./routes/migration.routes.js";
import { mobileRouter } from "./routes/mobile.routes.js";
import { offlineRouter } from "./routes/offline.routes.js";
import { offlineSyncRouter } from "./routes/offline-sync.routes.js";
import { operationsRouter } from "./routes/operations.routes.js";
import { paymentPublicRouter, paymentRouter } from "./routes/payment.routes.js";
import { posSettingsRouter } from "./routes/pos-settings.routes.js";
import { printDeviceRouter } from "./routes/print-device.routes.js";
import { publicBookingActionsRouter } from "./routes/public-booking-actions.routes.js";
import { qualityRouter } from "./routes/quality.routes.js";
import { dailyClosingRouter } from "./routes/daily-closing.routes.js";
import { reconciliationRouter } from "./routes/reconciliation.routes.js";
import { reputationRouter } from "./routes/reputation.routes.js";
import { realtimeRouter } from "./routes/realtime.routes.js";
import { resourceRouter } from "./routes/resource.routes.js";
import { saasRouter } from "./routes/saas.routes.js";
import { salonCostRouter } from "./routes/salon-cost.routes.js";
import { securityRouter } from "./routes/security.routes.js";
import { smartBookingRouter } from "./routes/smart-booking.routes.js";
import { slotReservationRouter } from "./routes/slot-reservation.routes.js";
import { staffSalesReportRouter } from "./routes/staff-sales-report.routes.js";
import { staffManagementRouter } from "./routes/staff-management.routes.js";
import { staffOsRouter } from "./routes/staff-os.routes.js";
import { staffEnterpriseRouter } from "./routes/staff-enterprise.routes.js";
import { staffSelfRouter } from "./routes/staff-self.routes.js";
import { superAdminRouter } from "./routes/super-admin.routes.js";
import { terminalRouter } from "./routes/terminal.routes.js";
import { whatsappRouter } from "./routes/whatsapp.routes.js";
import { waitlistRouter } from "./routes/waitlist.routes.js";
import { whiteLabelRouter } from "./routes/white-label.routes.js";
import { workflowEngineRouter } from "./routes/workflow-engine.routes.js";
import { zReportRouter } from "./routes/z-report.routes.js";

export function createApp() {
  initializeDatabaseRuntime();
  ensureAppointmentSystemSchema();
  ensureAppointmentActivitySchema();
  ensureEnterpriseSchedulerSchema();
  ensureClientMasterSchema();
  ensureStaffOsSchema();
  ensureStatutoryComplianceSchema();
  ensureInvoiceNotificationSchema();
  ensureReputationSchema();
  ensureAccountMasterSchema();
  ensureAccountLedgerSchema();
  ensureTransactionsSchema();
  ensureBalanceSheetSchema();
  ensureHardeningSchema();
  ensureAdvancedSchema();
  ensureAiWorkforceOsSchema();
  ensureSupplierCommandSchema();
  ensureEngagementSchema();
  ensurePurchaseBillDraftSchema();
  ensureProductUnitSchema();
  ensureInvoicePaymentCollectionSchema();
  ensureGrowthRankBotSchema();
  ensureLegacyRevenueSchema();
  ensureWaitlistSchema();
  ensureTwoFactorSchema();
  ensureSecurityAlertsSchema();
  ensureSecurityBlocklistSchema();
  ensureSecurityAdvancedSchema();
  const app = express();
  app.disable("x-powered-by");
  app.set("etag", false);
  app.use(
    cors({
      origin: (origin, callback) => {
        if (!origin || env.allowedOrigins.includes(origin) || /^http:\/\/127\.0\.0\.1:\d+$/.test(origin) || /^http:\/\/localhost:\d+$/.test(origin)) {
          callback(null, true);
          return;
        }
        callback(new Error("Origin not allowed by CORS"));
      }
    })
  );
  app.use(express.json({
    limit: env.requestBodyLimit,
    verify: (req, _res, buf) => {
      req.rawBody = buf?.length ? buf.toString("utf8") : "";
    }
  }));
  app.use(requestContext);
  app.use(securityBlocklistMiddleware);
  app.use(enterpriseSecurity);
  app.use(securityHeadersPlus);
  app.use(securityHoneypotRouter);
  app.use("/api", (req, res, next) => {
    delete req.headers["if-none-match"];
    delete req.headers["if-modified-since"];
    res.setHeader("Cache-Control", "no-store");
    res.vary("authorization");
    res.vary("x-tenant-id");
    res.vary("x-branch-id");
    next();
  });

  app.get("/api/versions", (_req, res) => {
    res.json({ current: "v1", supported: ["v1"], legacy: "/api", mobile: "/api/v1" });
  });
  app.use("/api/v1", mobileApiContext);
  app.get("/api/v1/health", (_req, res) => {
    res.json({ ok: true, service: "Aura Salon CRM/POS API", version: "v1", timestamp: new Date().toISOString() });
  });
  app.use("/api/v1", authRouter);
  app.use("/api/v1", twoFactorRouter);
  app.use("/api/v1", bookingPortalRouter);
  app.use("/api/v1", bookingPortalV2Router);
  app.use("/api/v1", publicBookingActionsRouter);
  app.use("/api/v1", bookingPaymentsPublicRouter);
  app.use("/api/v1", paymentPublicRouter);
  app.use("/api/v1", calendarPublicRouter);
  app.use("/api/v1", billingHealthRouter);
  app.use("/api/v1", authenticateJwt(), auditLogMiddleware);
  app.use("/api/v1", sessionKillSwitchMiddleware);
  app.use("/api/v1", subscriptionGuardMiddleware);
  app.use("/api/v1", idempotencyMiddleware);
  app.use("/api/v1", exportProtectionMiddleware);
  app.use("/api/v1", dashboardRouter);
  app.use("/api/v1", bookingAnalyticsRouter);
  app.use("/api/v1", bookingIntelligenceRouter);
  app.use("/api/v1", appointmentActivityRouter);
  app.use("/api/v1", appointmentSmsRouter);
  app.use("/api/v1", enterpriseSchedulerRouter);
  app.use("/api/v1", waitlistRouter);
  app.use("/api/v1", accountMasterRouter);
  app.use("/api/v1", transactionsRouter);
  app.use("/api/v1", balanceSheetRouter);
  app.use("/api/v1", balanceSheetHardeningRouter);
  app.use("/api/v1", balanceSheetAdvancedRouter);
  app.use("/api/v1", salonCostRouter);
  app.use("/api/v1", crmRouter);
  app.use("/api/v1", clientMasterRouter);
  app.use("/api/v1", gstRouter);
  app.use("/api/v1", statutoryComplianceRouter);
  app.use("/api/v1", billingRouter);
  app.use("/api/v1", billingAnalyticsRouter);
  app.use("/api/v1", commissionRouter);
  app.use("/api/v1", dailyClosingRouter);
  app.use("/api/v1", reconciliationRouter);
  app.use("/api/v1", offlineSyncRouter);
  app.use("/api/v1", corporateBillingRouter);
  app.use("/api/v1", giftCardRouter);
  app.use("/api/v1", discountApprovalRouter);
  app.use("/api/v1", invoiceLedgerRouter);
  app.use("/api/v1", invoiceNotificationRouter);
  app.use("/api/v1", terminalRouter);
  app.use("/api/v1", printDeviceRouter);
  app.use("/api/v1", zReportRouter);
  app.use("/api/v1", paymentRouter);
  app.use("/api/v1", posSettingsRouter);
  app.use("/api/v1", bookingPaymentsRouter);
  app.use("/api/v1", appointmentDepositGateRouter);
  app.use("/api/v1", legacyRevenueRouter);
  app.use("/api/v1", localizationPreferenceRouter);
  app.use("/api/v1", auditRouter);
  app.use("/api/v1", authenticateJwt(), mobileRouter);
  app.use("/api/v1", authenticateJwt(), realtimeRouter);
  app.use("/api/v1", authenticateJwt(), superAdminRouter);
  app.use("/api/v1", authenticateJwt(), saasRouter);
  app.use("/api/v1", authenticateJwt(), smartBookingRouter);
  app.use("/api/v1", securityAlertsRouter);
  app.use("/api/v1", securityBlocklistRouter);
  app.use("/api/v1", securityAdvancedRouter);
  app.use("/api/v1", authenticateJwt(), securityRouter);
  app.use("/api/v1", authenticateJwt(), offlineRouter);
  app.use("/api/v1", authenticateJwt(), whiteLabelRouter);
  app.use("/api/v1", authenticateJwt(), futureFeaturesRouter);
  app.use("/api/v1", authenticateJwt(), workflowEngineRouter);
  app.use("/api/v1", authenticateJwt(), financeEngineRouter);
  app.use("/api/v1", authenticateJwt(), customer360Router);
  app.use("/api/v1", authenticateJwt(), qualityRouter);
  app.use("/api/v1", authenticateJwt(), deploymentRouter);
  app.use("/api/v1", authenticateJwt(), ecosystemRouter);
  app.use("/api/v1", authenticateJwt(), analyticsRouter);
  app.use("/api/v1", authenticateJwt(), migrationRouter);
  app.use("/api/v1", authenticateJwt(), aiRouter);
  app.use("/api/v1", authenticateJwt(), aiMarketingRouter);
  app.use("/api/v1", authenticateJwt(), growthRankBotRouter);
  app.use("/api/v1", authenticateJwt(), whatsappRouter);
  app.use("/api/v1", authenticateJwt(), staffManagementRouter);
  app.use("/api/v1", authenticateJwt(), staffOsRouter);
  app.use("/api/v1", authenticateJwt(), staffEnterpriseRouter);
  app.use("/api/v1", authenticateJwt(), staffSelfRouter);
  app.use("/api/v1", authenticateJwt(), enterpriseCommandRouter);
  app.use("/api/v1", authenticateJwt(), engagementRouter);
  app.use("/api/v1", authenticateJwt(), inventoryIntelligenceRouter);
  app.use("/api/v1", authenticateJwt(), membershipEnterpriseRouter);
  app.use("/api/v1", authenticateJwt(), staffSalesReportRouter);
  app.use("/api/v1", authenticateJwt(), clientReportsRouter);
  app.use("/api/v1", authenticateJwt(), operationsRouter);
  app.use("/api/v1", authenticateJwt(), slotReservationRouter);
  app.use("/api/v1", authenticateJwt(), appointmentSafetyRouter);
  app.use("/api/v1", authenticateJwt(), reputationRouter);
  app.use("/api/v1", authenticateJwt(), resourceRouter);
  app.use("/api/v1", notFoundHandler);

  app.get("/api/health", (_req, res) => {
    res.json({ ok: true, service: "Aura Salon CRM/POS API", timestamp: new Date().toISOString() });
  });

  const legacyApiAuth = env.nodeEnv === "production" ? authenticateJwt() : (_req, _res, next) => next();
  app.use("/api", calendarPublicRouter);
  app.use("/api", bookingPaymentsPublicRouter);
  app.use("/api", paymentPublicRouter);
  app.use("/api", publicBookingActionsRouter);
  app.use("/api", billingHealthRouter);
  app.use("/api", staffSelfRouter);
  app.use("/api", legacyApiAuth);
  app.use("/api", auditLogMiddleware);
  app.use("/api", sessionKillSwitchMiddleware);
  app.use("/api", subscriptionGuardMiddleware);
  app.use("/api", idempotencyMiddleware);
  app.use("/api", exportProtectionMiddleware);
  app.use("/api", dashboardRouter);
  app.use("/api", bookingAnalyticsRouter);
  app.use("/api", bookingIntelligenceRouter);
  app.use("/api", appointmentActivityRouter);
  app.use("/api", appointmentSmsRouter);
  app.use("/api", enterpriseSchedulerRouter);
  app.use("/api", accountMasterRouter);
  app.use("/api", transactionsRouter);
  app.use("/api", balanceSheetRouter);
  app.use("/api", balanceSheetHardeningRouter);
  app.use("/api", balanceSheetAdvancedRouter);
  app.use("/api", salonCostRouter);
  app.use("/api", crmRouter);
  app.use("/api", clientMasterRouter);
  app.use("/api", gstRouter);
  app.use("/api", statutoryComplianceRouter);
  app.use("/api", billingRouter);
  app.use("/api", billingAnalyticsRouter);
  app.use("/api", commissionRouter);
  app.use("/api", dailyClosingRouter);
  app.use("/api", reconciliationRouter);
  app.use("/api", offlineSyncRouter);
  app.use("/api", corporateBillingRouter);
  app.use("/api", giftCardRouter);
  app.use("/api", discountApprovalRouter);
  app.use("/api", invoiceLedgerRouter);
  app.use("/api", invoiceNotificationRouter);
  app.use("/api", terminalRouter);
  app.use("/api", printDeviceRouter);
  app.use("/api", zReportRouter);
  app.use("/api", paymentRouter);
  app.use("/api", posSettingsRouter);
  app.use("/api", bookingPaymentsRouter);
  app.use("/api", appointmentDepositGateRouter);
  app.use("/api", legacyRevenueRouter);
  app.use("/api", localizationPreferenceRouter);
  app.use("/api", auditRouter);
  app.use("/api", superAdminRouter);
  app.use("/api", saasRouter);
  app.use("/api", smartBookingRouter);
  app.use("/api", twoFactorRouter);
  app.use("/api", securityAlertsRouter);
  app.use("/api", securityBlocklistRouter);
  app.use("/api", securityAdvancedRouter);
  app.use("/api", securityRouter);
  app.use("/api", offlineRouter);
  app.use("/api", whiteLabelRouter);
  app.use("/api", futureFeaturesRouter);
  app.use("/api", workflowEngineRouter);
  app.use("/api", financeEngineRouter);
  app.use("/api", customer360Router);
  app.use("/api", bookingPortalRouter);
  app.use("/api", bookingPortalV2Router);
  app.use("/api", qualityRouter);
  app.use("/api", deploymentRouter);
  app.use("/api", ecosystemRouter);
  app.use("/api", analyticsRouter);
  app.use("/api", migrationRouter);
  app.use("/api", aiRouter);
  app.use("/api", aiMarketingRouter);
  app.use("/api", growthRankBotRouter);
  app.use("/api", whatsappRouter);
  app.use("/api", staffManagementRouter);
  app.use("/api", staffOsRouter);
  app.use("/api", staffEnterpriseRouter);
  app.use("/api", enterpriseCommandRouter);
  app.use("/api", engagementRouter);
  app.use("/api", inventoryIntelligenceRouter);
  app.use("/api", membershipEnterpriseRouter);
  app.use("/api", staffSalesReportRouter);
  app.use("/api", clientReportsRouter);
  app.use("/api", operationsRouter);
  app.use("/api", slotReservationRouter);
  app.use("/api", appointmentSafetyRouter);
  app.use("/api", reputationRouter);
  app.use("/api", resourceRouter);

  const clientDist = resolveClientDist();
  if (clientDist) {
    app.use(express.static(clientDist));
    app.get(/^(?!\/api).*/, (_req, res) => {
      res.sendFile(join(clientDist, "index.html"));
    });
  }

  app.use(notFoundHandler);
  app.use(errorHandler);

  return app;
}

function resolveClientDist() {
  const candidates = [
    join(process.cwd(), "dist", "aura-salon-crm-pos", "browser"),
    join(process.cwd(), "dist", "aura-salon-crm-pos")
  ];
  return candidates.find((candidate) => existsSync(join(candidate, "index.html"))) || "";
}
