import { CommonModule } from "@angular/common";
import { Component, HostListener, OnInit, computed, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerGeneralSettings, OwnerSettingsResponse } from "./owner-administration.models";

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<article class="adm-page" [attr.aria-busy]="loading()">
  <header class="adm-hero"><div><p class="adm-eyebrow">Administration · General settings</p><h1>One workspace, thoughtfully configured.</h1><p>Only fields supported by the existing general settings contract are editable. Specialist settings remain with their authoritative modules.</p></div><div class="adm-actions"><label class="adm-field">Settings scope<select [ngModel]="scope()" (ngModelChange)="changeScope($event)" [disabled]="loading()||saving()"><option value="">All branches</option>@for(branch of context.branches();track branch.id){<option [value]="branch.id">{{branch.name}}</option>}</select></label>@if(!error()||response()){<button class="adm-button" [disabled]="loading()||saving()" (click)="reload()">↻ Reload</button>}</div></header>
  @if(message()){<p class="adm-message" [class.error]="messageError()" [attr.role]="messageError()?'alert':'status'">{{message()}}</p>}
  @if(loading()&&!response()){<div class="adm-skeleton"><i></i><i></i><i></i></div>}@else if(error()&&!response()){<section class="adm-state" role="alert"><span>!</span><h2>Settings unavailable</h2><p>{{error()}}</p><button class="adm-button" (click)="load()">Try again</button></section>}@else if(draft();as settings){
  <section class="adm-settings"><nav class="adm-section-nav" aria-label="Settings sections"><a href="/owner/settings#business">Business profile</a><a href="/owner/settings#regional">Regional & time</a><a href="/owner/settings#branches">Branch behavior</a><a href="/owner/settings#interface">Interface</a><a href="/owner/settings#defaults">Owner defaults</a><a href="/owner/settings#availability">Availability</a></nav>
  <div class="adm-settings-body">
    <section class="adm-settings-section" id="business"><header><h2>Business profile</h2><p>Workspace identity and landing behavior from the general settings contract.</p></header><div class="adm-setting-grid"><label class="adm-field">Workspace name<input [(ngModel)]="settings.workspace.workspaceName" (ngModelChange)="changed()" maxlength="120" [attr.aria-invalid]="validation().workspaceName"></label><label class="adm-field">Default landing page<select [(ngModel)]="settings.workspace.defaultLandingPage" (ngModelChange)="changed()"><option value="dashboard">Dashboard</option><option value="pos">Billing Access</option><option value="appointments">Appointments</option><option value="clients">Clients</option><option value="reports">Reports</option></select></label><label class="adm-switch">Fast POS enabled<input type="checkbox" [(ngModel)]="settings.workspace.fastPosEnabled" (ngModelChange)="changed()"></label></div><p class="adm-error" *ngIf="validation().workspaceName">Workspace name is required.</p></section>
    <section class="adm-settings-section" id="regional"><header><h2>Regional, date & time</h2><p>Timezone and formatting remain explicit; business dates use the configured timezone.</p></header><div class="adm-setting-grid"><label class="adm-field">Country<input [(ngModel)]="settings.localization.country" (ngModelChange)="changed()"></label><label class="adm-field">Language<input [(ngModel)]="settings.localization.language" (ngModelChange)="changed()"></label><label class="adm-field">Timezone<input [(ngModel)]="settings.localization.timezone" (ngModelChange)="changed()" placeholder="Asia/Kolkata" [attr.aria-invalid]="validation().timezone"></label><label class="adm-field">Currency<input [(ngModel)]="settings.localization.currency" (ngModelChange)="changed()" maxlength="3"></label><label class="adm-field">Locale<input [(ngModel)]="settings.localization.locale" (ngModelChange)="changed()"></label><label class="adm-field">Date format<select [(ngModel)]="settings.dateTime.dateFormat" (ngModelChange)="changed()"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label class="adm-field">Time format<select [(ngModel)]="settings.dateTime.timeFormat" (ngModelChange)="changed()"><option value="12h">12 hour</option><option value="24h">24 hour</option></select></label><label class="adm-field">Week starts on<select [(ngModel)]="settings.dateTime.weekStartsOn" (ngModelChange)="changed()"><option>Monday</option><option>Sunday</option></select></label><label class="adm-field">Business day starts<input type="number" min="0" max="23" [(ngModel)]="settings.dateTime.businessDayStartHour" (ngModelChange)="changed()" [attr.aria-invalid]="validation().businessHour"></label></div><p class="adm-error" *ngIf="validation().timezone">Enter an IANA timezone such as Asia/Kolkata.</p><p class="adm-error" *ngIf="validation().businessHour">Business day start must be a whole hour from 0 to 23.</p></section>
    <section class="adm-settings-section" id="branches"><header><h2>Branch behavior</h2><p>Controls selection behavior only; backend branch assignments remain authoritative.</p></header><div class="adm-setting-grid"><label class="adm-switch">Remember last branch<input type="checkbox" [(ngModel)]="settings.branchBehavior.rememberLastBranch" (ngModelChange)="changed()"></label><label class="adm-switch">Require branch selection<input type="checkbox" [(ngModel)]="settings.branchBehavior.requireBranchSelection" (ngModelChange)="changed()"></label><label class="adm-switch">Allow branch switch<input type="checkbox" [(ngModel)]="settings.branchBehavior.allowBranchSwitch" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="interface"><header><h2>Interface</h2><p>General workspace presentation supported by the current contract.</p></header><div class="adm-setting-grid"><label class="adm-switch">Compact mode<input type="checkbox" [(ngModel)]="settings.interface.compactMode" (ngModelChange)="changed()"></label><label class="adm-switch">Show module badges<input type="checkbox" [(ngModel)]="settings.interface.showModuleBadges" (ngModelChange)="changed()"></label><label class="adm-switch">Enable command search<input type="checkbox" [(ngModel)]="settings.interface.enableCommandSearch" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="defaults"><header><h2>Owner defaults</h2><p>Saved defaults from the general settings contract.</p></header><div class="adm-setting-grid"><label class="adm-switch">Refresh reports on open<input type="checkbox" [(ngModel)]="settings.defaults.refreshReportsOnOpen" (ngModelChange)="changed()"></label><label class="adm-switch">Owner notifications<input type="checkbox" [(ngModel)]="settings.defaults.ownerNotifications" (ngModelChange)="changed()"></label><label class="adm-switch">Staff hints<input type="checkbox" [(ngModel)]="settings.defaults.staffHints" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="availability"><header><h2>Specialist settings</h2><p>These areas are not presented as editable because another backend contract owns them.</p></header><div class="adm-capabilities">@for(item of unavailable();track item.key){<div><strong>{{label(item.key)}}</strong><p>{{item.value}}</p></div>}</div></section>
    <div class="adm-sticky-save"><span>@if(dirty()){<strong>Unsaved changes</strong> · Leave protection is active.}@else if(response()?.audit?.lastChangedAt){Saved {{date(response()!.audit.lastChangedAt)}} by {{response()!.audit.lastChangedBy}}}@else{No saved changes recorded.}</span><div class="adm-actions"><button class="adm-button" [disabled]="!dirty()||saving()" (click)="discard()">Discard</button><button class="adm-button primary" [disabled]="!dirty()||saving()||invalid()" (click)="save()">{{saving()?'Saving…':'Save settings'}}</button></div></div>
  </div></section>}
</article>
`,styleUrls:["./owner-shell.styles.css","./owner-administration.css"]})
export class OwnerSettingsPage implements OnInit{
  readonly loading=signal(true);readonly saving=signal(false);readonly error=signal("");readonly message=signal("");readonly messageError=signal(false);readonly scope=signal("");readonly response=signal<OwnerSettingsResponse|null>(null);readonly draft=signal<OwnerGeneralSettings|null>(null);readonly baseline=signal("");
  private request=0;
  readonly dirty=computed(()=>!!this.draft()&&JSON.stringify(this.draft())!==this.baseline());readonly validation=computed(()=>{const s=this.draft();return{workspaceName:!s?.workspace.workspaceName.trim(),timezone:!!s&&!/^[A-Za-z_]+\/[A-Za-z_+-]+(?:\/[A-Za-z_+-]+)?$/.test(s.localization.timezone),businessHour:!!s&&(!Number.isInteger(Number(s.dateTime.businessDayStartHour))||Number(s.dateTime.businessDayStartHour)<0||Number(s.dateTime.businessDayStartHour)>23)}});readonly invalid=computed(()=>Object.values(this.validation()).some(Boolean));readonly unavailable=computed(()=>Object.entries(this.response()?.unavailableSections||{}).map(([key,value])=>({key,value})));
  constructor(private readonly api:OwnerAppService,readonly context:OwnerContextService){}ngOnInit(){this.scope.set(this.context.selectedBranchId());void this.load();}
  async load(){const request=++this.request,scope=this.scope();this.loading.set(true);this.error.set("");try{const data=await this.api.administrationSettings(scope);if(request===this.request&&scope===this.scope()){this.response.set(data);this.setDraft(data.settings);}}catch{if(request===this.request)this.error.set("Aura could not load general settings for this scope.");}finally{if(request===this.request)this.loading.set(false);}}
  reload(){if(this.dirty()&&!confirm("Discard unsaved settings and reload the saved version?"))return;void this.load();}
  changeScope(value:string){if(this.dirty()&&!confirm("Discard unsaved settings before changing scope?"))return;this.scope.set(value);this.message.set("");void this.load();}
  changed(){const value=this.draft();if(value)this.draft.set(structuredClone(value));}
  discard(){const settings=this.response()?.settings;if(settings)this.setDraft(settings);this.message.set("Unsaved changes discarded.");this.messageError.set(false);}
   async save(){const settings=this.draft(),scope=this.scope();if(!settings||!this.dirty()||this.invalid()||this.saving())return;this.saving.set(true);this.message.set("");try{const data=await this.api.saveAdministrationSettings(scope,settings);this.response.set({...data,supportedSections:this.response()?.supportedSections||[],unavailableSections:this.response()?.unavailableSections||{}});this.setDraft(data.settings);if(scope===this.context.selectedBranchId())this.context.applySettings(data.settings);this.messageError.set(false);this.message.set(data.preservedUnknownSettings?"Settings saved. Unrecognized stored settings were preserved.":"Settings saved.");}catch{this.messageError.set(true);this.message.set("Settings were not saved. Review the fields or retry after refreshing.");}finally{this.saving.set(false);}}
  canLeave(){return!this.dirty()||confirm("You have unsaved general settings. Leave without saving?");}
  @HostListener("window:beforeunload",["$event"])beforeUnload(event:BeforeUnloadEvent){if(!this.dirty())return;event.preventDefault();event.returnValue="";}
  private setDraft(settings:OwnerGeneralSettings){const copy=structuredClone(settings);this.draft.set(copy);this.baseline.set(JSON.stringify(copy));}
  label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}date(value:string){return this.context.formatDateTime(value);}
}
