import { CommonModule } from "@angular/common";
import { Component, ElementRef, HostListener, OnInit, ViewChild, computed, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerAccessAdministration, OwnerAdministrationRole, OwnerAdministrationUser, OwnerRoleWrite, OwnerUserWrite } from "./owner-administration.models";

type AccessDialog="role"|"user"|"disable"|null;
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<article class="adm-page" [attr.aria-busy]="loading()" [attr.inert]="dialog()?'' : null">
  <header class="adm-hero"><div><p class="adm-eyebrow">Administration · Access</p><h1>Give the right access. Keep control.</h1><p>Roles use Aura’s live permission catalogue. User access is limited to branches assigned to your owner account.</p></div><div class="adm-actions">@if(!error()||data()){<button class="adm-button" [disabled]="loading()" (click)="load(true)">↻ Refresh</button>}<button class="adm-button primary" (click)="openRole(null,false,$event)">＋ New role</button><button class="adm-button primary" (click)="openUser(null,$event)">＋ Add user</button></div></header>
  @if(message()){<p class="adm-message" [class.error]="messageError()" [attr.role]="messageError()?'alert':'status'">{{message()}}</p>}
  <div class="adm-toolbar"><div class="adm-tabs" role="tablist" aria-label="Access views"><button role="tab" [class.active]="view()==='roles'" [attr.aria-selected]="view()==='roles'" (click)="view.set('roles')">Roles</button><button role="tab" [class.active]="view()==='users'" [attr.aria-selected]="view()==='users'" (click)="view.set('users')">Users</button></div><label class="adm-field grow" for="access-search">Search<input id="access-search" type="search" [ngModel]="query()" (ngModelChange)="query.set($event)" [placeholder]="view()==='roles'?'Role name or description':'Name, email, login or role'"></label></div>
  @if(loading()&&!data()){<div class="adm-skeleton"><i></i><i></i><i></i></div>}@else if(error()&&!data()){<section class="adm-state" role="alert"><span>!</span><h2>Access catalogue unavailable</h2><p>{{error()}}</p><button class="adm-button" (click)="load()">Try again</button></section>}@else if(view()==='roles'){
    <section class="adm-layout"><section class="adm-panel"><header class="adm-panel-head"><h2>Role catalogue</h2><span>{{roles().length}} shown</span></header><div class="adm-list">@for(role of roles();track role.role){<button [class.selected]="selectedRole()?.role===role.role" (click)="selectedRole.set(role)"><span class="adm-avatar">{{role.name.charAt(0)}}</span><span><strong>{{role.name}}</strong><small>{{role.description||role.role}} · {{role.permissionKeys.length}} grants</small></span><span class="adm-status" [attr.data-active]="role.status==='active'">{{role.status}}</span></button>}@empty{<div class="adm-state"><span>—</span><h2>No matching roles</h2><p>Try a different search.</p></div>}</div></section>
    <section class="adm-panel">@if(selectedRole();as role){<div class="adm-detail"><div class="adm-detail-hero"><div><p class="adm-eyebrow">{{role.isSystem?'System role':'Custom role'}}</p><h2>{{role.name}}</h2><p>{{role.description||'No role description recorded.'}}</p></div><div class="adm-actions">@if(role.editable){<button class="adm-button" (click)="openRole(role,false,$event)">Edit</button>}<button class="adm-button" (click)="openRole(role,true,$event)">Duplicate</button></div></div>@if(role.isSystem){<p class="adm-note"><strong>Protected system role</strong>System role grants are visible for review and cannot be edited here.</p>}<div class="adm-permissions">@for(group of visibleGroups(role);track group.key){<section class="adm-permission-group"><header><h3>{{group.label}}</h3><span class="adm-status">{{grantsInGroup(role,group.key)}} granted</span></header><div>@for(item of group.items;track item.key){@if(role.permissionKeys.includes(item.key)){<div class="adm-check"><span>✓</span><span>{{item.label}}<small *ngIf="item.sensitive">Sensitive access</small></span></div>}}</div></section>}@empty{<p class="adm-note">No catalogue permissions are recorded for this role.</p>}</div></div>}@else{<div class="adm-state"><span>↗</span><h2>Select a role</h2><p>Review its effective catalogue grants and sensitive access.</p></div>}</section></section>
  }@else{
    <section class="adm-layout"><section class="adm-panel"><header class="adm-panel-head"><h2>Tenant users</h2><span>{{users().length}} shown</span></header><div class="adm-list">@for(user of users();track user.id){<button [class.selected]="selectedUser()?.id===user.id" (click)="selectedUser.set(user)"><span class="adm-avatar">{{user.name.charAt(0)}}</span><span><strong>{{user.name}}</strong><small>{{user.email}} · {{roleName(user.role)}}</small></span><span class="adm-status" [attr.data-active]="user.status==='active'">{{user.status}}</span></button>}@empty{<div class="adm-state"><span>—</span><h2>No matching users</h2><p>Try a different search.</p></div>}</div></section>
    <section class="adm-panel">@if(selectedUser();as user){<div class="adm-detail"><div class="adm-detail-hero"><div><p class="adm-eyebrow">Tenant user</p><h2>{{user.name}}</h2><p>{{user.email}} · {{user.loginId||'No login ID'}}</p></div><div class="adm-actions"><button class="adm-button" [disabled]="isCurrentOwner(user)" (click)="openUser(user,$event)">Edit access</button><button class="adm-button danger" [disabled]="isCurrentOwner(user)||user.status!=='active'" (click)="openDisable(user,$event)">Disable</button></div></div><dl class="adm-facts"><div><dt>Role</dt><dd>{{roleName(user.role)}}</dd></div><div><dt>Status</dt><dd>{{user.status}}{{user.isLocked?' · Locked':''}}</dd></div><div><dt>Branch access</dt><dd>{{branchNames(user.branchIds)}}</dd></div><div><dt>Active sessions</dt><dd>{{user.activeSessions}}</dd></div><div><dt>Permission version</dt><dd>{{user.permissionVersion}}</dd></div><div><dt>Last login</dt><dd>{{user.lastLoginAt?date(user.lastLoginAt):'Not recorded'}}</dd></div></dl>@if(isCurrentOwner(user)){<p class="adm-note"><strong>Your owner access is protected</strong>This session cannot remove its owner role or disable itself. The backend also prevents removal of the last active owner or administrator.</p>}@else{<p class="adm-note"><strong>Session protection</strong>Role, branch, status and password changes increment permissionVersion so older access tokens stop working.</p>}</div>}@else{<div class="adm-state"><span>↗</span><h2>Select a user</h2><p>Review role, branch scope and session protection.</p></div>}</section></section>
  }
</article>
@if(dialog()){<button class="adm-backdrop" (click)="close()" aria-label="Close dialog"></button><section class="adm-dialog" role="dialog" aria-modal="true" aria-labelledby="access-dialog-title" #modal tabindex="-1"><header><div><p class="adm-eyebrow">Roles & permissions</p><h2 id="access-dialog-title">{{dialogTitle()}}</h2></div><button class="adm-close" (click)="close()" aria-label="Close">×</button></header>
  @if(dialog()==='role'){<form id="access-form" class="adm-form" (ngSubmit)="saveRole()"><label class="adm-field">Role key<input name="roleKey" [(ngModel)]="roleForm.role" required pattern="[A-Za-z][A-Za-z0-9_-]{2,40}" [readonly]="editingRole()&&!duplicating()"></label><label class="adm-field">Display name<input name="roleName" [(ngModel)]="roleForm.name" required maxlength="100"></label><label class="adm-field full">Description<textarea name="roleDescription" [(ngModel)]="roleForm.description" maxlength="300"></textarea></label><label class="adm-field">Status<select name="roleStatus" [(ngModel)]="roleForm.status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><p class="adm-note full"><strong>Sensitive permissions</strong>Security, settings, finance, payroll, refunds, branches and destructive actions can materially change the business. Grant only what this role needs.</p>@if(roleError()){<p class="adm-message error full" role="alert">{{roleError()}}</p>}<div class="adm-permissions full"><div class="adm-all-toggle"><button type="button" class="adm-button sm" (click)="toggleAllPermissions()">{{allPermissionsGranted()?'Revoke All':'Grant All'}}</button><span class="adm-toggle-count">{{roleForm.permissionKeys.length}}/{{allPermissionCount()}} permissions</span></div>@for(group of data()?.permissionGroups||[];track group.key){<section class="adm-permission-group"><header><h3>{{group.label}}</h3><div class="adm-group-actions"><button type="button" class="adm-button sm" (click)="toggleGroup(group.key)">{{allInGroupGranted(group.key)?'Revoke':'Grant all'}}</button><span>{{selectedInGroup(group.key)}}/{{group.items.length}}</span></div></header><div>@for(item of group.items;track item.key){<label class="adm-check"><input type="checkbox" [checked]="roleForm.permissionKeys.includes(item.key)" (change)="togglePermission(item.key)"><span>{{item.label}}<small *ngIf="item.sensitive">Sensitive</small></span></label>}</div></section>}</div></form>}
  @if(dialog()==='user'){<form id="access-form" class="adm-form" (ngSubmit)="saveUser()"><label class="adm-field">Full name<input name="userName" [(ngModel)]="userForm.name" required maxlength="120"></label><label class="adm-field">Email<input name="userEmail" type="email" [(ngModel)]="userForm.email" required></label><label class="adm-field">Login ID<input name="loginId" [(ngModel)]="userForm.loginId" maxlength="100"></label><label class="adm-field">Role<select name="userRole" [(ngModel)]="userForm.role" required><option *ngFor="let role of assignableRoles()" [value]="role.role">{{role.name}}</option></select></label><label class="adm-field">Status<select name="userStatus" [(ngModel)]="userForm.status"><option value="active">Active</option><option value="hidden">Hidden</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select></label><label class="adm-field">{{editingUser()?'New password (optional)':'Temporary password'}}<input name="userPassword" type="password" [(ngModel)]="userForm.password" [required]="!editingUser()" minlength="10" autocomplete="new-password"></label><fieldset class="full" style="border:0;padding:0;margin:0"><legend class="adm-eyebrow">Branch access</legend><div class="adm-check-list">@for(branch of data()?.branches||[];track branch.id){<label class="adm-check"><input type="checkbox" [checked]="userForm.branchIds.includes(branch.id)" (change)="toggleBranch(branch.id)"><span>{{branch.name}}<small>{{branch.city}}</small></span></label>}</div></fieldset><p class="adm-note full"><strong>Scope is server validated</strong>Only tenant branches assigned to your owner account can be granted. Non-administrator roles require at least one branch.</p></form>}
  @if(dialog()==='disable'){<div class="adm-form"><p class="adm-note full"><strong>Disable {{selectedUser()?.name}}?</strong>The user will be signed out when permissionVersion changes. Their tenant record and audit history remain intact.</p></div>}
  <footer><button class="adm-button" (click)="close()">Cancel</button><button class="adm-button" [class.primary]="dialog()!=='disable'" [class.danger]="dialog()==='disable'" [attr.form]="dialog()==='disable'?null:'access-form'" [attr.type]="dialog()==='disable'?'button':'submit'" [disabled]="submitting()" (click)="dialog()==='disable'&&disableUser()">{{submitting()?'Saving…':dialog()==='disable'?'Disable user':'Save changes'}}</button></footer></section>}
`,styleUrls:["./owner-shell.styles.css","./owner-administration.css"]})
export class OwnerRolesPermissionsPage implements OnInit{
  @ViewChild("modal")modal?:ElementRef<HTMLElement>;readonly loading=signal(true);readonly error=signal("");readonly message=signal("");readonly messageError=signal(false);readonly roleError=signal("");readonly data=signal<OwnerAccessAdministration|null>(null);readonly view=signal<"roles"|"users">("roles");readonly query=signal("");readonly selectedRole=signal<OwnerAdministrationRole|null>(null);readonly selectedUser=signal<OwnerAdministrationUser|null>(null);readonly dialog=signal<AccessDialog>(null);readonly submitting=signal(false);readonly editingRole=signal(false);readonly duplicating=signal(false);readonly editingUser=signal(false);private trigger:HTMLElement|null=null;
  roleForm:OwnerRoleWrite={role:"",name:"",description:"",status:"active",permissionKeys:[]};userForm:OwnerUserWrite={name:"",loginId:"",email:"",role:"staff",branchIds:[],status:"active",password:""};
  readonly roles=computed(()=>{const q=this.query().trim().toLowerCase();return(this.data()?.roles||[]).filter(r=>!q||`${r.name} ${r.role} ${r.description}`.toLowerCase().includes(q));});readonly users=computed(()=>{const q=this.query().trim().toLowerCase();return(this.data()?.users||[]).filter(u=>!q||`${u.name} ${u.email} ${u.loginId} ${u.role}`.toLowerCase().includes(q));});  readonly assignableRoles=computed(()=>(this.data()?.roles||[]).filter(r=>r.status==="active"));
  readonly allPermissionKeys=computed(()=>{const groups=this.data()?.permissionGroups||[];const keys:string[]=[];groups.forEach(g=>g.items.forEach(i=>keys.push(i.key)));return keys;});
  readonly allPermissionCount=computed(()=>this.allPermissionKeys().length);
  readonly allPermissionsGranted=computed(()=>{const all=this.allPermissionKeys();return all.length>0&&all.every(k=>this.roleForm.permissionKeys.includes(k));});
  allInGroupGranted(groupKey:string){const group=(this.data()?.permissionGroups||[]).find(g=>g.key===groupKey);if(!group)return false;return group.items.every(i=>this.roleForm.permissionKeys.includes(i.key));}
  constructor(readonly api:OwnerAppService,private context:OwnerContextService){}ngOnInit(){void this.load();}
  async load(background=false){if(!background)this.loading.set(true);this.error.set("");try{const data=await this.api.administrationAccess();this.apply(data);if(background)this.show("Access catalogue refreshed.");}catch{this.error.set("Aura could not load the owner access catalogue.");}finally{this.loading.set(false);}}
  private apply(data:OwnerAccessAdministration){this.data.set(data);this.selectedRole.set(data.roles.find(r=>r.role===this.selectedRole()?.role)||data.roles[0]||null);this.selectedUser.set(data.users.find(u=>u.id===this.selectedUser()?.id)||data.users[0]||null);}
  openRole(role:OwnerAdministrationRole|null,duplicate:boolean,event:Event){this.trigger=event.currentTarget as HTMLElement;this.roleError.set("");this.editingRole.set(!!role&&!duplicate);this.duplicating.set(duplicate);this.roleForm=role?{role:duplicate?`${role.role}Copy`:role.role,name:duplicate?`${role.name} copy`:role.name,description:role.description,status:"active",permissionKeys:[...role.permissionKeys]}:{role:"",name:"",description:"",status:"active",permissionKeys:[]};this.open("role");}
  openUser(user:OwnerAdministrationUser|null,event:Event){if(user&&this.isCurrentOwner(user))return;this.trigger=event.currentTarget as HTMLElement;this.editingUser.set(!!user);if(user)this.selectedUser.set(user);this.userForm=user?{name:user.name,loginId:user.loginId,email:user.email,role:user.role,branchIds:[...user.branchIds],status:user.status,password:""}:{name:"",loginId:"",email:"",role:this.assignableRoles().find(r=>r.role==="staff")?.role||this.assignableRoles()[0]?.role||"staff",branchIds:[],status:"active",password:""};this.open("user");}
  openDisable(user:OwnerAdministrationUser,event:Event){this.trigger=event.currentTarget as HTMLElement;this.selectedUser.set(user);this.open("disable");}private open(value:Exclude<AccessDialog,null>){this.dialog.set(value);document.documentElement.classList.add("staff-overlay-open");setTimeout(()=>this.modal?.nativeElement.focus());}close(){this.dialog.set(null);document.documentElement.classList.remove("staff-overlay-open");setTimeout(()=>this.trigger?.focus());}
  togglePermission(key:string){this.roleError.set("");this.roleForm={...this.roleForm,permissionKeys:this.roleForm.permissionKeys.includes(key)?this.roleForm.permissionKeys.filter(v=>v!==key):[...this.roleForm.permissionKeys,key]};}
  toggleAllPermissions(){const all=this.allPermissionKeys();const hasAll=all.every(k=>this.roleForm.permissionKeys.includes(k));this.roleError.set("");this.roleForm={...this.roleForm,permissionKeys:hasAll?[]:[...all]};}
  toggleGroup(groupKey:string){const group=(this.data()?.permissionGroups||[]).find(g=>g.key===groupKey);if(!group)return;const groupKeys=group.items.map(i=>i.key);const hasAll=groupKeys.every(k=>this.roleForm.permissionKeys.includes(k));const updated=hasAll?this.roleForm.permissionKeys.filter(k=>!groupKeys.includes(k)):[...new Set([...this.roleForm.permissionKeys,...groupKeys])];this.roleError.set("");this.roleForm={...this.roleForm,permissionKeys:updated};}
  toggleBranch(id:string){this.userForm={...this.userForm,branchIds:this.userForm.branchIds.includes(id)?this.userForm.branchIds.filter(v=>v!==id):[...this.userForm.branchIds,id]};}
  async saveRole(){if(this.submitting()||!this.roleForm.role.trim()||!this.roleForm.name.trim())return;if(!this.roleForm.permissionKeys.length){this.roleError.set("Choose at least one permission before saving this role.");return;}this.roleError.set("");this.submitting.set(true);try{const result=await this.api.saveAdministrationRole(this.roleForm);this.apply(result.access);this.selectedRole.set(result.access.roles.find(r=>r.role===this.roleForm.role)||null);this.close();this.show(result.invalidatedUsers?`Role saved. ${result.invalidatedUsers} assigned user session${result.invalidatedUsers===1?"":"s"} invalidated.`:"Role saved.");}catch{this.roleError.set("The role was not saved. Check the role key and catalogue permissions.");}finally{this.submitting.set(false);}}
  async saveUser(){if(this.submitting()||!this.userForm.name.trim()||!this.userForm.email.trim()||(!this.editingUser()&&String(this.userForm.password||"").length<10))return;this.submitting.set(true);try{const payload={...this.userForm,...(!this.userForm.password?{password:undefined}:{})};const result=this.editingUser()?await this.api.updateAdministrationUser(this.selectedUser()!.id,payload):await this.api.createAdministrationUser(payload);this.apply(result.access);this.selectedUser.set(result.user);this.close();this.show("User access saved. Changed sessions are invalidated by the backend.");}catch{this.show("The user change was not saved. Check role, branch access and last-owner protections.",true);}finally{this.submitting.set(false);}}
  async disableUser(){const user=this.selectedUser();if(!user||this.submitting()||this.isCurrentOwner(user))return;this.submitting.set(true);try{const result=await this.api.updateAdministrationUser(user.id,{status:"disabled"});this.apply(result.access);this.selectedUser.set(result.user);this.close();this.show("User disabled. Their record and audit history were retained.");}catch{this.show("The user could not be disabled. At least one active owner or administrator must remain.",true);}finally{this.submitting.set(false);}}
  visibleGroups(role:OwnerAdministrationRole){return(this.data()?.permissionGroups||[]).filter(g=>g.items.some(i=>role.permissionKeys.includes(i.key)));}grantsInGroup(role:OwnerAdministrationRole,key:string){return this.data()?.permissionGroups.find(g=>g.key===key)?.items.filter(i=>role.permissionKeys.includes(i.key)).length||0;}selectedInGroup(key:string){return this.data()?.permissionGroups.find(g=>g.key===key)?.items.filter(i=>this.roleForm.permissionKeys.includes(i.key)).length||0;}
  roleName(key:string){return this.data()?.roles.find(r=>r.role===key)?.name||key;}branchNames(ids:string[]){const names=ids.map(id=>this.data()?.branches.find(b=>b.id===id)?.name||id);return names.length?names.join(", "):"No branch access";}isCurrentOwner(user:OwnerAdministrationUser){return user.id===this.api.user()?.id;}date(value:string){return this.context.formatDateTime(value);}dialogTitle(){return this.dialog()==="role"?(this.duplicating()?"Duplicate role":this.editingRole()?"Edit role":"Create role"):this.dialog()==="user"?(this.editingUser()?"Edit user access":"Create tenant user"):"Confirm disable";}private show(value:string,error=false){this.message.set(value);this.messageError.set(error);}
  @HostListener("window:keydown",["$event"])key(event:KeyboardEvent){if(!this.dialog())return;if(event.key==="Escape"){event.preventDefault();this.close();return;}if(event.key!=="Tab")return;const nodes=this.modal?.nativeElement.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
}
