export const CASE_STUDIES = [
  { slug: "three-branch-no-show-reduction", title: "How a 3-branch salon can reduce no-shows with connected reminders", segment: "Multi-branch salon", metric: "No-show reduction playbook", outcome: "Automated reminders, deposits and waitlist recovery" },
  { slug: "premium-salon-retention-system", title: "How a premium salon can turn consultation notes into repeat visits", segment: "Premium salon", metric: "Retention workflow", outcome: "Client 360, preferences and rebooking nudges" },
  { slug: "inventory-waste-control", title: "How service recipes can reduce salon inventory waste", segment: "High-volume salon", metric: "Stock control workflow", outcome: "Batch tracking, expiry alerts and service usage" },
] as const;

export const PRODUCT_TOUR_ITEMS = [
  { slug: "booking-calendar", title: "Booking calendar", body: "Manage online bookings, walk-ins, waitlists, reminders and service durations in one calendar." },
  { slug: "gst-pos", title: "GST POS billing", body: "Raise GST-ready invoices, split UPI/card/cash payments and reconcile daily closing." },
  { slug: "client-360", title: "Client 360 CRM", body: "See visit history, preferences, notes, allergies, packages, wallet and follow-ups." },
  { slug: "staff-app", title: "Staff app", body: "Give stylists appointments, shifts, attendance, targets and commission visibility." },
  { slug: "inventory", title: "Inventory control", body: "Track batches, expiry, service recipes, reorder points and branch transfers." },
  { slug: "owner-dashboard", title: "Owner dashboard", body: "Review revenue, utilisation, collections, stock alerts and retention queues." },
] as const;

export const CORE_PRODUCT_PAGES = [
  { slug: "salon-pos-software", title: "Salon POS Software", audience: "salons that need fast GST billing, split payments and daily closing", angle: "Turn every service, product sale, package redemption and refund into a clean POS workflow." },
  { slug: "salon-crm-software", title: "Salon CRM Software", audience: "salons that want client history, preferences and retention follow-ups", angle: "Give every client a complete memory across visits, notes, packages, wallet and campaigns." },
  { slug: "salon-booking-software", title: "Salon Booking Software", audience: "salons that need online booking, reminders, calendars and waitlists", angle: "Manage appointment demand without depending on phone calls, notebooks or scattered WhatsApp chats." },
  { slug: "salon-management-software", title: "Salon Management Software", audience: "owners who want booking, billing, CRM, staff, inventory and reports together", angle: "Run the salon from one operating system instead of disconnected tools." },
  { slug: "beauty-salon-software", title: "Beauty Salon Software", audience: "beauty salons and parlours", angle: "Connect services, packages, staff, GST billing and repeat-visit marketing." },
  { slug: "spa-management-software", title: "Spa Management Software", audience: "spas, wellness centers and therapy studios", angle: "Coordinate rooms, therapists, prepaid packages, inventory usage and client notes." },
  { slug: "barber-shop-software", title: "Barber Shop Software", audience: "barber shops and men's grooming studios", angle: "Handle quick walk-ins, repeat clients, memberships, staff turns and fast billing." },
  { slug: "salon-chain-software", title: "Salon Chain Software", audience: "multi-branch salon chains", angle: "Standardise branch operations, permissions, staff performance, stock movement and owner reporting." },
  { slug: "salon-franchise-software", title: "Salon Franchise Software", audience: "franchise salon networks", angle: "Protect brand process consistency while giving every branch operational visibility." },
  { slug: "hair-salon-software", title: "Hair Salon Software", audience: "hair salons, colour studios and styling teams", angle: "Track colour notes, rebooking, stylist schedules, service durations and retail product sales." },
  { slug: "nail-salon-software", title: "Nail Salon Software", audience: "nail salons and nail art studios", angle: "Manage technician availability, package visits, add-ons, hygiene checks and retail sales." },
  { slug: "skin-clinic-software", title: "Skin Clinic Software", audience: "skin clinics and aesthetic studios", angle: "Record consultation notes, session plans, consent, follow-ups and package redemptions." },
  { slug: "bridal-salon-software", title: "Bridal Salon Software", audience: "bridal makeup and premium styling teams", angle: "Coordinate trial sessions, event dates, packages, deposits, artists and client preferences." },
  { slug: "salon-inventory-software", title: "Salon Inventory Software", audience: "salons that need stock, batch, expiry and service recipe control", angle: "Know what is used, wasted, transferred and reordered before inventory becomes leakage." },
] as const;

export const FEATURE_DETAIL_PAGES = [
  { group: "appointments", slug: "online-booking", title: "Online Booking", problem: "clients want to book without calling the front desk" },
  { group: "appointments", slug: "appointment-calendar", title: "Appointment Calendar", problem: "teams need one view of staff, services and capacity" },
  { group: "appointments", slug: "waitlist-management", title: "Waitlist Management", problem: "cancelled slots should be recovered instead of lost" },
  { group: "appointments", slug: "whatsapp-reminders", title: "WhatsApp Appointment Reminders", problem: "no-shows and late arrivals reduce chair utilisation" },
  { group: "appointments", slug: "walk-in-queue", title: "Walk-in Queue", problem: "walk-ins need a fair, visible service order" },
  { group: "billing", slug: "gst-billing", title: "GST Billing", problem: "salon invoices need clean tax, discounts and payment mode records" },
  { group: "billing", slug: "split-payments", title: "Split Payments", problem: "clients often pay using UPI, card, cash, wallet or packages together" },
  { group: "billing", slug: "package-redemption", title: "Package Redemption", problem: "prepaid value needs clear usage and liability tracking" },
  { group: "billing", slug: "daily-closing", title: "Daily Closing", problem: "owners need bills, refunds and collections reconciled every day" },
  { group: "billing", slug: "refund-controls", title: "Refund Controls", problem: "refunds and credits need reasons, permissions and audit trails" },
  { group: "client-crm", slug: "client-profiles", title: "Client Profiles", problem: "staff need visit history and preferences before service starts" },
  { group: "client-crm", slug: "consultation-forms", title: "Consultation Forms", problem: "important client notes should not stay in notebooks or chat" },
  { group: "client-crm", slug: "loyalty-wallet", title: "Loyalty Wallet", problem: "rewards and wallet credit need controlled redemption rules" },
  { group: "client-crm", slug: "client-segmentation", title: "Client Segmentation", problem: "marketing should target behaviour, not every client equally" },
  { group: "client-crm", slug: "feedback-and-reviews", title: "Feedback and Reviews", problem: "happy clients should be guided into feedback and repeat visits" },
  { group: "staff-management", slug: "staff-attendance", title: "Staff Attendance", problem: "attendance, late marks and shifts need reliable records" },
  { group: "staff-management", slug: "staff-commission", title: "Staff Commission", problem: "commission rules should be transparent and measurable" },
  { group: "staff-management", slug: "shift-roster", title: "Shift Roster", problem: "teams need clear schedules across days and branches" },
  { group: "staff-management", slug: "payroll-workflows", title: "Payroll Workflows", problem: "salary, incentives and deductions need clean inputs" },
  { group: "staff-management", slug: "target-tracking", title: "Target Tracking", problem: "owners need staff and branch goals visible before month end" },
  { group: "inventory", slug: "batch-inventory", title: "Batch Inventory", problem: "products need batch, purchase and usage traceability" },
  { group: "inventory", slug: "expiry-alerts", title: "Expiry Alerts", problem: "expired or ageing stock creates waste and service risk" },
  { group: "inventory", slug: "reorder-points", title: "Reorder Points", problem: "stockouts should be prevented before busy days" },
  { group: "inventory", slug: "service-recipes", title: "Service Recipes", problem: "product usage needs to connect to service costing" },
  { group: "inventory", slug: "branch-transfers", title: "Branch Transfers", problem: "multi-branch stock movement needs controlled records" },
  { group: "marketing-ai", slug: "marketing-automation", title: "Marketing Automation", problem: "repeat visit campaigns should not depend on manual reminders" },
  { group: "marketing-ai", slug: "birthday-campaigns", title: "Birthday Campaigns", problem: "client dates should become personalised retention moments" },
  { group: "marketing-ai", slug: "winback-campaigns", title: "Win-back Campaigns", problem: "inactive clients need targeted recovery workflows" },
  { group: "marketing-ai", slug: "referral-campaigns", title: "Referral Campaigns", problem: "loyal clients should help generate new bookings" },
  { group: "marketing-ai", slug: "review-requests", title: "Review Requests", problem: "post-visit feedback needs a timely follow-up process" },
  { group: "finance", slug: "owner-dashboard", title: "Owner Dashboard", problem: "owners need revenue, collections and leakage visible quickly" },
  { group: "finance", slug: "profit-tracking", title: "Profit Tracking", problem: "revenue alone does not show margin, cost or cashflow" },
  { group: "finance", slug: "cashflow-reports", title: "Cashflow Reports", problem: "salons need clarity on inflow, outflow and daily closing" },
  { group: "compliance", slug: "role-permissions", title: "Role Permissions", problem: "staff should only access the workflows they need" },
  { group: "compliance", slug: "audit-trails", title: "Audit Trails", problem: "bill edits, refunds and discounts need traceability" },
  { group: "white-label", slug: "branded-customer-app", title: "Branded Customer App", problem: "premium salons want bookings and loyalty under their own brand" },
] as const;

export const CALCULATORS = [
  { slug: "salon-revenue", title: "Salon revenue calculator", inputs: ["Average ticket", "Bills per day", "Working days"], formula: "average ticket x bills per day x working days" },
  { slug: "no-show-loss", title: "No-show loss calculator", inputs: ["Average ticket", "No-shows per week"], formula: "average ticket x no-shows x 4" },
  { slug: "staff-commission", title: "Staff commission calculator", inputs: ["Service revenue", "Commission rate"], formula: "service revenue x commission rate" },
  { slug: "inventory-reorder", title: "Inventory reorder calculator", inputs: ["Daily usage", "Supplier lead time", "Safety stock"], formula: "daily usage x lead time + safety stock" },
  { slug: "salon-profit-margin", title: "Salon profit margin calculator", inputs: ["Service price", "Product cost", "Staff cost"], formula: "service price - product cost - staff cost" },
  { slug: "chair-utilisation", title: "Chair utilisation calculator", inputs: ["Booked hours", "Available hours"], formula: "booked hours / available hours" },
  { slug: "average-ticket", title: "Average ticket calculator", inputs: ["Revenue", "Bills"], formula: "revenue / bills" },
  { slug: "package-liability", title: "Package liability calculator", inputs: ["Unused sessions", "Value per session"], formula: "unused sessions x value per session" },
  { slug: "retail-attachment", title: "Retail attachment calculator", inputs: ["Retail bills", "Total bills"], formula: "retail bills / total bills" },
  { slug: "customer-retention", title: "Customer retention calculator", inputs: ["Returning clients", "Total clients"], formula: "returning clients / total clients" },
  { slug: "salon-break-even", title: "Salon break-even calculator", inputs: ["Fixed costs", "Average margin"], formula: "fixed costs / average margin" },
  { slug: "marketing-roi", title: "Marketing ROI calculator", inputs: ["Campaign revenue", "Campaign cost"], formula: "(revenue - cost) / cost" },
] as const;

export const TEMPLATES = [
  { slug: "staff-attendance-policy", title: "Staff attendance policy template", category: "Staff" },
  { slug: "salon-gst-checklist", title: "Salon GST checklist", category: "Compliance" },
  { slug: "bridal-package-checklist", title: "Bridal package checklist", category: "Growth" },
  { slug: "inventory-audit-sheet", title: "Inventory audit sheet", category: "Operations" },
  { slug: "client-consultation-form", title: "Client consultation form", category: "CRM" },
  { slug: "salon-opening-checklist", title: "Salon opening checklist", category: "Operations" },
  { slug: "salon-closing-checklist", title: "Salon closing checklist", category: "Operations" },
  { slug: "staff-commission-policy", title: "Staff commission policy template", category: "Staff" },
  { slug: "refund-policy", title: "Salon refund policy template", category: "Compliance" },
  { slug: "hygiene-checklist", title: "Salon hygiene checklist", category: "Compliance" },
  { slug: "salon-marketing-calendar", title: "Salon marketing calendar", category: "Marketing" },
  { slug: "salon-price-list-template", title: "Salon price list template", category: "Growth" },
  { slug: "shift-roster-template", title: "Shift roster template", category: "Staff" },
  { slug: "package-redemption-log", title: "Package redemption log", category: "Operations" },
  { slug: "client-feedback-form", title: "Client feedback form", category: "CRM" },
] as const;

export const GLOSSARY_TERMS = [
  { slug: "salon-crm", term: "Salon CRM", definition: "A system for storing client profiles, visit history, preferences, notes, packages and follow-up workflows." },
  { slug: "client-360", term: "Client 360", definition: "A complete view of a salon client across bookings, billing, notes, preferences, packages and feedback." },
  { slug: "average-ticket", term: "Average ticket", definition: "Revenue divided by number of bills over a period." },
  { slug: "reorder-point", term: "Reorder point", definition: "The stock level at which a salon should reorder a product based on usage, lead time and safety stock." },
  { slug: "service-recipe", term: "Service recipe", definition: "Estimated product usage for a specific salon service, used for inventory deduction and costing." },
  { slug: "no-show-rate", term: "No-show rate", definition: "The percentage of booked appointments where clients do not arrive and do not cancel in time." },
  { slug: "chair-utilisation", term: "Chair utilisation", definition: "Booked salon chair hours divided by available chair hours over a period." },
  { slug: "retail-attachment", term: "Retail attachment", definition: "The percentage of service bills that include at least one retail product sale." },
  { slug: "package-liability", term: "Package liability", definition: "Unused prepaid package value that still represents future services owed to clients." },
  { slug: "daily-closing", term: "Daily closing", definition: "The end-of-day reconciliation of bills, payments, cash, refunds and adjustments." },
  { slug: "waitlist", term: "Waitlist", definition: "A list of clients who want earlier appointment slots when cancellations open capacity." },
  { slug: "win-back-campaign", term: "Win-back campaign", definition: "A targeted message flow for clients who have not visited within a defined period." },
  { slug: "stylist-utilisation", term: "Stylist utilisation", definition: "Booked working time for a stylist compared with their available working time." },
  { slug: "wallet-credit", term: "Wallet credit", definition: "Prepaid or reward value stored against a client profile for future billing use." },
  { slug: "gst-pos", term: "GST POS", definition: "A point-of-sale workflow that records GST-ready invoices, payment modes, discounts and tax context." },
  { slug: "branch-transfer", term: "Branch transfer", definition: "Movement of stock from one salon branch to another before placing a new purchase order." },
  { slug: "salon-pos", term: "Salon POS", definition: "Billing software for salons that records services, products, discounts, taxes and payment modes." },
  { slug: "gst-invoice", term: "GST invoice", definition: "An invoice that includes GST tax details, taxable value, invoice number and customer or business context where required." },
  { slug: "staff-commission", term: "Staff commission", definition: "Variable payout calculated from service revenue, product sales, targets or custom salon rules." },
  { slug: "loyalty-wallet", term: "Loyalty wallet", definition: "Client reward value stored in the CRM and applied to future visits under defined rules." },
  { slug: "membership", term: "Membership", definition: "A prepaid or recurring salon plan that gives clients defined benefits, credits or discounts." },
  { slug: "service-package", term: "Service package", definition: "A bundle of prepaid salon services that clients redeem over multiple visits." },
  { slug: "consultation-form", term: "Consultation form", definition: "A structured form for recording client needs, preferences, allergies, consent and service notes." },
  { slug: "online-booking", term: "Online booking", definition: "A client-facing booking flow where customers select services, staff, date and time without calling the salon." },
  { slug: "appointment-reminder", term: "Appointment reminder", definition: "An automated message sent before an appointment to reduce missed visits and late arrivals." },
  { slug: "rebooking-rate", term: "Rebooking rate", definition: "The percentage of clients who book their next visit before or soon after completing a service." },
  { slug: "client-retention", term: "Client retention", definition: "The ability of a salon to bring clients back repeatedly over a defined period." },
  { slug: "churn", term: "Client churn", definition: "Clients who stop visiting after a previous appointment or membership period." },
  { slug: "rfm-segmentation", term: "RFM segmentation", definition: "Grouping clients by recency, frequency and monetary value for targeted marketing." },
  { slug: "birthday-campaign", term: "Birthday campaign", definition: "A campaign that sends birthday offers or greetings to clients based on CRM profile dates." },
  { slug: "review-request", term: "Review request", definition: "A post-visit message asking satisfied clients to share feedback or leave a public review." },
  { slug: "front-desk", term: "Front desk", definition: "The salon role responsible for appointments, billing, client communication and daily coordination." },
  { slug: "daily-sales-report", term: "Daily sales report", definition: "A report showing revenue, bills, collections, refunds and payment modes for a day." },
  { slug: "cash-reconciliation", term: "Cash reconciliation", definition: "Matching physical cash with POS cash collections and adjustments at day end." },
  { slug: "split-payment", term: "Split payment", definition: "A bill paid using more than one mode such as cash, UPI, card, wallet or package credit." },
  { slug: "discount-approval", term: "Discount approval", definition: "A control where discounts above a rule require manager or owner approval." },
  { slug: "refund-note", term: "Refund note", definition: "A record explaining why money or credit was returned to a client." },
  { slug: "stock-ledger", term: "Stock ledger", definition: "A running record of product stock movement including purchases, usage, transfers and adjustments." },
  { slug: "batch-tracking", term: "Batch tracking", definition: "Inventory tracking by product batch to monitor expiry, purchase source and usage." },
  { slug: "expiry-alert", term: "Expiry alert", definition: "A warning when salon inventory is nearing expiry or has crossed the allowed usage date." },
  { slug: "supplier-lead-time", term: "Supplier lead time", definition: "The time between placing a purchase order and receiving stock from a supplier." },
  { slug: "safety-stock", term: "Safety stock", definition: "Extra inventory kept to protect against demand spikes or supplier delays." },
  { slug: "service-costing", term: "Service costing", definition: "Estimating the product and staff cost behind a salon service to understand margins." },
  { slug: "gross-margin", term: "Gross margin", definition: "Revenue left after direct service or product costs before overheads." },
  { slug: "net-profit", term: "Net profit", definition: "Profit left after direct costs, staff, rent, utilities, marketing and other operating expenses." },
  { slug: "break-even", term: "Break-even", definition: "The sales level where salon revenue covers fixed and variable costs." },
  { slug: "owner-dashboard", term: "Owner dashboard", definition: "A summary screen showing key salon metrics such as revenue, collections, utilisation and retention." },
  { slug: "branch-dashboard", term: "Branch dashboard", definition: "A dashboard comparing performance, staff, stock and collections by salon location." },
  { slug: "role-permission", term: "Role permission", definition: "Access control that decides what each salon team role can view or change." },
  { slug: "audit-trail", term: "Audit trail", definition: "A log of important changes such as bill edits, discounts, refunds and permission updates." },
  { slug: "salon-sop", term: "Salon SOP", definition: "A repeatable operating procedure used by the team for consistent service and admin work." },
  { slug: "shift-roster", term: "Shift roster", definition: "A staff schedule showing who is working across dates, times and branches." },
  { slug: "attendance", term: "Attendance", definition: "A record of staff presence, leave, late arrivals and working time." },
  { slug: "payroll", term: "Payroll", definition: "The process of calculating salary, incentives, deductions and payouts for salon staff." },
  { slug: "target-tracking", term: "Target tracking", definition: "Monitoring staff or branch performance against sales, service or retail goals." },
  { slug: "retail-sales", term: "Retail sales", definition: "Product sales made alongside or separate from salon services." },
  { slug: "upsell", term: "Upsell", definition: "Offering a higher-value service or add-on that improves client outcome and average ticket." },
  { slug: "cross-sell", term: "Cross-sell", definition: "Offering a related product or service based on client needs and visit context." },
  { slug: "client-preference", term: "Client preference", definition: "Saved details such as stylist choice, product preference, shade, pressure, allergies or beverage choices." },
  { slug: "skin-patch-test", term: "Skin patch test", definition: "A safety check used before certain colour or chemical services to reduce reaction risk." },
  { slug: "consent-record", term: "Consent record", definition: "A saved confirmation that a client agreed to a service, policy, treatment or communication." },
  { slug: "data-export", term: "Data export", definition: "Downloading salon data such as clients, bills, stock or reports for review or backup." },
  { slug: "multi-branch", term: "Multi-branch", definition: "A salon business operating more than one location under the same brand or ownership." },
  { slug: "franchise-salon", term: "Franchise salon", definition: "A salon model where different operators run branches under a shared brand and process system." },
  { slug: "white-label-app", term: "White-label app", definition: "A branded app experience that appears under the salon's own identity." },
  { slug: "customer-app", term: "Customer app", definition: "A client-facing app or portal for bookings, packages, loyalty, wallet and profile access." },
  { slug: "staff-app", term: "Staff app", definition: "A mobile workflow for staff appointments, attendance, notes, targets and commissions." },
  { slug: "lead-source", term: "Lead source", definition: "The channel where a client or enquiry came from, such as Instagram, referral, walk-in or ads." },
  { slug: "marketing-roi", term: "Marketing ROI", definition: "Return on campaign spend calculated by comparing campaign revenue with campaign cost." },
  { slug: "campaign-segment", term: "Campaign segment", definition: "A client group selected for a message based on behaviour, value, service history or lifecycle stage." },
  { slug: "walk-in", term: "Walk-in", definition: "A client visit that arrives without a prior appointment." },
  { slug: "queue-management", term: "Queue management", definition: "Managing walk-ins, waiting clients and service order to reduce confusion at front desk." },
  { slug: "resource-utilisation", term: "Resource utilisation", definition: "Booked time or usage of rooms, chairs, equipment or staff compared with available capacity." },
  { slug: "service-menu", term: "Service menu", definition: "The structured list of salon services with price, duration, tax and staff eligibility." },
  { slug: "price-book", term: "Price book", definition: "A controlled service and product pricing list used by POS and booking workflows." },
  { slug: "package-redemption", term: "Package redemption", definition: "Using a prepaid package credit against a completed service visit." },
] as const;

export const RESOURCE_HUBS = [
  { slug: "billing", title: "Billing resources", focus: "GST POS, invoices, refunds and reconciliation" },
  { slug: "staff", title: "Staff resources", focus: "Attendance, shifts, payroll, commissions and reviews" },
  { slug: "inventory", title: "Inventory resources", focus: "Batch, expiry, reorder, transfers and service recipes" },
  { slug: "marketing", title: "Marketing resources", focus: "WhatsApp, win-backs, loyalty, reviews and campaigns" },
  { slug: "crm", title: "CRM resources", focus: "Client 360, consultations, preferences and retention" },
  { slug: "appointments", title: "Appointments resources", focus: "Online booking, reminders, waitlists and calendar control" },
  { slug: "finance", title: "Finance resources", focus: "Daily closing, cashflow, margins and owner dashboards" },
  { slug: "compliance", title: "Compliance resources", focus: "GST, consent, privacy, refunds and audit trails" },
  { slug: "salon-growth", title: "Salon growth resources", focus: "Revenue, pricing, memberships and expansion workflows" },
  { slug: "salon-operations", title: "Salon operations resources", focus: "Manager routines, service menus, queues and branch operations" },
] as const;

export const EXTRA_CITIES = ["kolkata", "chennai", "lucknow", "indore", "surat", "nagpur", "kochi", "bhopal", "ludhiana", "noida", "gurgaon", "coimbatore", "visakhapatnam", "vadodara", "patna", "guwahati", "bhubaneswar"] as const;

export const USE_CASES = [
  "reduce-salon-no-shows", "increase-salon-revenue", "manage-salon-staff", "gst-billing-for-salons", "manage-salon-inventory", "automate-salon-marketing", "client-retention", "multi-branch-salon-management", "salon-daily-closing", "staff-commission-tracking", "package-redemption-tracking", "salon-loyalty-program", "online-booking-for-salons", "waitlist-management", "salon-cashflow-control", "inventory-expiry-control", "bridal-package-management", "client-consultation-records", "salon-review-generation", "salon-referral-tracking", "staff-attendance-control", "salon-roster-planning", "retail-product-sales", "salon-membership-management", "customer-winback-campaigns", "owner-dashboard-reporting", "front-desk-operations", "discount-approval-control", "vendor-purchase-planning", "salon-franchise-operations"
].map((slug) => ({ slug, title: slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" "), focus: "Connect the workflow in Aura so the salon team can act consistently and owners can measure progress." })) as { slug: string; title: string; focus: string }[];

export const INTEGRATIONS = [
  "whatsapp", "upi", "razorpay", "stripe", "google-calendar", "google-business-profile", "tally", "zoho-books", "gmail", "meta-ads", "instagram", "facebook", "google-sheets", "payment-links", "webhooks"
].map((slug) => ({ slug, name: slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" "), status: slug === "whatsapp" || slug === "upi" ? "workflow-supported" : "setup-dependent" })) as { slug: string; name: string; status: string }[];

export const PERSONAS = [
  { slug: "salon-owner", title: "Salon Owner", focus: "owner dashboards, profit, staff control and branch visibility" },
  { slug: "salon-manager", title: "Salon Manager", focus: "appointments, daily closing, staff coordination and client experience" },
  { slug: "front-desk-team", title: "Front Desk Team", focus: "booking, billing, payments, packages and client follow-ups" },
  { slug: "stylist", title: "Stylist", focus: "appointments, notes, attendance, targets and commissions" },
  { slug: "franchise-owner", title: "Franchise Owner", focus: "multi-location reporting, SOPs, permissions and brand consistency" },
  { slug: "finance-team", title: "Finance Team", focus: "GST billing, reconciliation, expenses and daily closing" },
  { slug: "marketing-manager", title: "Marketing Manager", focus: "segments, WhatsApp campaigns, win-backs and loyalty" },
  { slug: "inventory-manager", title: "Inventory Manager", focus: "stock, batches, expiry, transfers and reorder planning" },
] as const;

export const HELP_TOPICS = [
  "getting-started", "importing-clients", "setting-up-services", "setting-up-gst", "staff-commission-setup", "inventory-setup", "online-booking-setup", "whatsapp-reminders", "reports", "data-security", "adding-staff", "creating-shifts", "configuring-payments", "daily-closing", "package-setup", "wallet-setup", "loyalty-setup", "discount-rules", "refunds-and-credits", "stock-transfers", "expiry-alerts", "reorder-points", "client-notes", "consultation-forms", "review-requests", "birthday-campaigns", "winback-campaigns", "branch-management", "role-permissions", "exporting-data", "audit-trails", "tax-reports", "invoice-numbering", "customer-app-setup", "staff-app-setup", "owner-dashboard", "front-desk-workflow", "calendar-settings", "waitlist-setup", "support-and-training"
].map((slug) => ({ slug, title: slug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ") })) as { slug: string; title: string }[];
