export const ROUTE_MESSAGES: Record<"en" | "hi", Record<string, string>> = {
  en: {
    "common.backHome": "Back to home", "common.backBlog": "Back to journal", "common.feature": "Feature", "common.month": "/mo", "common.custom": "Custom", "common.loading": "Sending...", "common.error": "Something went wrong. Please try again.",
    "features.badge": "Features", "features.pageTitle": "Everything your salon needs", "features.pageBody": "Explore every Aura workspace—designed for real salon operations, not generic business workflows.", "features.learn": "Explore workspace",
    "feature.spotlight": "Feature spotlight", "feature.capabilities": "Capabilities", "feature.what": "What you get", "feature.whatBody": "Focused tools designed for day-to-day salon operations.", "feature.experience": "See {name} in action", "feature.experienceBody": "Book a personal walkthrough to see how {name} fits your salon.", "feature.demo": "Book a demo",
    "pricing.badge": "Pricing", "pricing.pageTitle": "Simple, transparent pricing", "pricing.pageBody": "Start with the plan that fits today and scale when your operation grows.", "pricing.monthly": "Monthly", "pricing.annual": "Annual", "pricing.toggle": "Toggle annual billing", "pricing.save": "Save 20%", "pricing.billed": "Billed {amount}/year", "pricing.compare": "Compare", "pricing.compareTitle": "Plan comparison", "pricing.compareBody": "See what is included in each plan.", "pricing.feature": "Feature", "pricing.faq": "FAQ", "pricing.faqTitle": "Frequently asked questions", "pricing.faqBody": "Clear answers about Aura plans and billing.", "pricing.upTo5": "Up to 5", "pricing.unlimited": "Unlimited",
    "pricing.tier.0.name": "Starter", "pricing.tier.1.name": "Growth", "pricing.tier.2.name": "Enterprise", "pricing.tier.0.desc": "For a single salon building its digital foundation", "pricing.tier.1.desc": "For growing salons that need automation and control", "pricing.tier.2.desc": "For salon chains, franchises and custom operations", "pricing.start": "Start free trial", "pricing.sales": "Contact sales",
    "customers.badge": "Customers", "customers.title": "Built around the way salons work", "customers.body": "Stories from salon teams using Aura across their daily operation.", "customers.cases": "Case studies", "customers.casesTitle": "Operational change, clearly measured", "customers.casesBody": "A before-and-after view of moving the salon onto one system.", "customers.before": "Before", "customers.after": "After", "customers.revenue": "Monthly revenue", "customers.clients": "Active clients", "customers.staff": "Team size", "customers.noShows": "No-shows", "customers.ctaTitle": "Bring your salon onto one connected system", "customers.ctaBody": "See Aura with your own workflow in a personal walkthrough.",
    "about.story": "Our story", "about.titleA": "Building a clearer", "about.titleB": "future for salons", "about.body": "Aura began with a simple belief: salon teams deserve software that understands their work—not another generic business tool.", "about.mission": "Our mission", "about.missionBody": "Give every Indian salon intelligent, approachable technology that handles operational detail and leaves teams more time for clients.", "about.timeline": "Product path", "about.journey": "How the system is taking shape", "about.journeyBody": "Confirmed product foundations, without invented adoption milestones.", "about.join": "Build a better salon operation", "about.joinBody": "We work with forward-thinking salon teams who care about detail.", "about.contact": "Contact us", "about.foundation0": "Connected front desk", "about.foundation1": "India-ready checkout", "about.foundation2": "Scoped operations", "about.foundation3": "Business-time events",
    "contact.badge": "Contact", "contact.title": "Let’s talk about your salon", "contact.body": "Ask a question, arrange a demo, or discuss a multi-branch operation.", "contact.name": "Your name", "contact.email": "Email", "contact.phone": "Phone", "contact.salon": "Salon name", "contact.message": "Message", "contact.send": "Send message", "contact.sent": "Message sent", "contact.sentBody": "Thank you. Your message was delivered for our team to review and follow up.", "contact.another": "Send another message", "contact.requiredName": "Name is required", "contact.requiredEmail": "Email is required", "contact.validEmail": "Enter a valid email", "contact.requiredMessage": "Message is required", "contact.shortMessage": "Write at least 10 characters", "contact.deliveryMissing": "Contact delivery is not configured. Please email hello@aurasalon.in while RESEND_API_KEY and CONTACT_EMAIL are set.", "contact.office": "Office", "contact.quick": "Quick links", "contact.schedule": "Schedule a demo", "contact.viewFeatures": "View features", "contact.viewPricing": "See pricing",
    "demo.badge": "Book a demo", "demo.titleA": "See Aura", "demo.titleB": "with your workflow", "demo.body": "A focused 15-minute walkthrough shaped around your salon, team and branches.", "demo.name": "Your name", "demo.email": "Email", "demo.phone": "Phone", "demo.salon": "Salon name", "demo.size": "Salon size", "demo.date": "Preferred date", "demo.time": "Preferred time", "demo.selectTime": "Select time", "demo.book": "Book my demo", "demo.expect": "What to expect", "demo.quick": "Focused and practical", "demo.quickBody": "No preparation needed. Bring the questions that matter to your operation.", "demo.done": "Request received", "demo.doneBody": "Your request was delivered. Our team will contact {email} to confirm {time} on {date}.",
    "blog.badge": "Journal", "blog.title": "Useful thinking for salon owners", "blog.body": "Practical guides on operations, clients, teams, stock and growth.", "blog.all": "All", "blog.featured": "Featured", "blog.read": "Read article", "blog.empty": "No articles in this category yet.", "blog.postMissing": "Article not found",
    "notFound.title": "Page not found", "notFound.body": "This page may have moved. Use one of these links to continue.", "notFound.home": "Home", "notFound.features": "Features", "notFound.pricing": "Pricing", "notFound.back": "Go back",
    "compare.badge": "Why Aura", "compare.title": "Aura and the alternatives", "compare.body": "A practical comparison for Indian salon operations.", "compare.feature": "Feature", "compare.local": "Local tools", "compare.note": "Fresha may charge commission on online bookings. Vagaro pricing is in USD and is not designed around Indian operations.",
    "testimonials.badge": "Salon stories", "testimonials.title": "What salon teams value", "testimonials.body": "Experiences shared by salon owners and managers using Aura.", "testimonials.prev": "Previous story", "testimonials.next": "Next story", "testimonials.go": "Go to story {number}",
    "stats.0": "Appointments booked", "stats.1": "Salons using Aura", "stats.2": "Transactions processed", "stats.3": "Uptime commitment",
    "overlay.close": "Close", "overlay.email": "Enter your email", "overlay.noSpam": "No spam. Unsubscribe anytime.", "overlay.whatsapp": "Need help? Chat with us", "overlay.chat": "Chat on WhatsApp", "overlay.top": "Back to top", "video.play": "Play video", "video.pause": "Pause video", "video.mute": "Mute video", "video.unmute": "Unmute video", "video.label": "Aura product walkthrough"
  },
  hi: {
    "common.backHome": "होम पर लौटें", "common.backBlog": "जर्नल पर लौटें", "common.feature": "फ़ीचर", "common.month": "/माह", "common.custom": "कस्टम", "common.loading": "भेजा जा रहा है...", "common.error": "कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।",
    "features.badge": "फ़ीचर्स", "features.pageTitle": "सैलून के हर ज़रूरी काम के लिए", "features.pageBody": "Aura के सभी वर्कस्पेस देखें—सामान्य बिज़नेस टूल नहीं, असली सैलून ऑपरेशंस के लिए बनाए गए।", "features.learn": "वर्कस्पेस देखें",
    "feature.spotlight": "फ़ीचर स्पॉटलाइट", "feature.capabilities": "क्षमताएँ", "feature.what": "आपको क्या मिलता है", "feature.whatBody": "रोज़ाना सैलून संचालन के लिए केंद्रित टूल।", "feature.experience": "{name} को काम करते देखें", "feature.experienceBody": "पर्सनल वॉकथ्रू में देखें कि {name} आपके सैलून के साथ कैसे फिट बैठता है।", "feature.demo": "डेमो बुक करें",
    "pricing.badge": "प्लान", "pricing.pageTitle": "साफ़ और सरल प्राइसिंग", "pricing.pageBody": "आज की ज़रूरत के अनुसार शुरू करें और ऑपरेशन बढ़ने पर आसानी से स्केल करें।", "pricing.monthly": "मासिक", "pricing.annual": "वार्षिक", "pricing.toggle": "वार्षिक बिलिंग चुनें", "pricing.save": "20% बचत", "pricing.billed": "सालाना {amount} बिल", "pricing.compare": "तुलना", "pricing.compareTitle": "प्लान की तुलना", "pricing.compareBody": "हर प्लान में क्या शामिल है, साफ़ तौर पर देखें।", "pricing.feature": "फ़ीचर", "pricing.faq": "सवाल-जवाब", "pricing.faqTitle": "अक्सर पूछे जाने वाले सवाल", "pricing.faqBody": "Aura के प्लान और बिलिंग से जुड़ी साफ़ जानकारी।", "pricing.upTo5": "5 तक", "pricing.unlimited": "अनलिमिटेड",
    "pricing.tier.0.name": "Starter", "pricing.tier.1.name": "Growth", "pricing.tier.2.name": "Enterprise", "pricing.tier.0.desc": "डिजिटल शुरुआत कर रहे एक सैलून के लिए", "pricing.tier.1.desc": "ऑटोमेशन और बेहतर कंट्रोल चाहने वाले बढ़ते सैलून के लिए", "pricing.tier.2.desc": "सैलून चेन, फ्रैंचाइज़ और कस्टम ऑपरेशंस के लिए", "pricing.start": "फ्री ट्रायल शुरू करें", "pricing.sales": "सेल्स से बात करें",
    "customers.badge": "ग्राहक", "customers.title": "सैलून के काम करने के तरीके के अनुसार", "customers.body": "Aura के साथ रोज़ाना ऑपरेशन संभाल रही सैलून टीमों के अनुभव।", "customers.cases": "केस स्टडी", "customers.casesTitle": "ऑपरेशनल बदलाव, साफ़ नतीजे", "customers.casesBody": "सैलून को एक सिस्टम पर लाने से पहले और बाद की तस्वीर।", "customers.before": "पहले", "customers.after": "बाद में", "customers.revenue": "मासिक आय", "customers.clients": "एक्टिव क्लाइंट", "customers.staff": "टीम साइज़", "customers.noShows": "नो-शो", "customers.ctaTitle": "अपने सैलून को एक जुड़े सिस्टम पर लाएँ", "customers.ctaBody": "पर्सनल वॉकथ्रू में Aura को अपने वर्कफ़्लो के साथ देखें।",
    "about.story": "हमारी कहानी", "about.titleA": "सैलून के लिए एक", "about.titleB": "ज़्यादा स्पष्ट भविष्य", "about.body": "Aura एक सरल सोच से शुरू हुआ: सैलून टीम को ऐसा सॉफ्टवेयर मिलना चाहिए जो उनके काम को समझे—सिर्फ़ एक और सामान्य बिज़नेस टूल नहीं।", "about.mission": "हमारा मिशन", "about.missionBody": "हर भारतीय सैलून को समझदार और आसान तकनीक देना, ताकि ऑपरेशनल बारीकियाँ सिस्टम संभाले और टीम क्लाइंट पर ध्यान दे सके।", "about.timeline": "प्रोडक्ट पथ", "about.journey": "सिस्टम कैसे आकार ले रहा है", "about.journeyBody": "बिना बनाए हुए adoption milestone के पक्की प्रोडक्ट नींव।", "about.join": "बेहतर सैलून ऑपरेशन बनाएँ", "about.joinBody": "हम उन सैलून टीमों के साथ काम करते हैं जो हर बारीकी की परवाह करती हैं।", "about.contact": "संपर्क करें", "about.foundation0": "जुड़ा फ्रंट डेस्क", "about.foundation1": "भारत-रेडी चेकआउट", "about.foundation2": "सीमित और सुरक्षित ऑपरेशन", "about.foundation3": "बिज़नेस-टाइम इवेंट",
    "contact.badge": "संपर्क", "contact.title": "आपके सैलून के बारे में बात करें", "contact.body": "सवाल पूछें, डेमो तय करें या मल्टी-ब्रांच ऑपरेशन पर चर्चा करें।", "contact.name": "आपका नाम", "contact.email": "ईमेल", "contact.phone": "फ़ोन", "contact.salon": "सैलून का नाम", "contact.message": "मैसेज", "contact.send": "मैसेज भेजें", "contact.sent": "मैसेज भेज दिया गया", "contact.sentBody": "धन्यवाद। आपका मैसेज हमारी टीम की समीक्षा और आगे संपर्क के लिए पहुँच गया है।", "contact.another": "दूसरा मैसेज भेजें", "contact.requiredName": "नाम ज़रूरी है", "contact.requiredEmail": "ईमेल ज़रूरी है", "contact.validEmail": "सही ईमेल दर्ज करें", "contact.requiredMessage": "मैसेज ज़रूरी है", "contact.shortMessage": "कम से कम 10 अक्षर लिखें", "contact.deliveryMissing": "कॉन्टैक्ट डिलीवरी कॉन्फ़िगर नहीं है। RESEND_API_KEY और CONTACT_EMAIL सेट होने तक hello@aurasalon.in पर ईमेल करें।", "contact.office": "ऑफिस", "contact.quick": "क्विक लिंक", "contact.schedule": "डेमो तय करें", "contact.viewFeatures": "फ़ीचर्स देखें", "contact.viewPricing": "प्लान देखें",
    "demo.badge": "डेमो बुक करें", "demo.titleA": "Aura को अपने", "demo.titleB": "वर्कफ़्लो के साथ देखें", "demo.body": "आपके सैलून, टीम और ब्रांच के अनुसार 15 मिनट का केंद्रित वॉकथ्रू।", "demo.name": "आपका नाम", "demo.email": "ईमेल", "demo.phone": "फ़ोन", "demo.salon": "सैलून का नाम", "demo.size": "सैलून साइज़", "demo.date": "पसंदीदा तारीख", "demo.time": "पसंदीदा समय", "demo.selectTime": "समय चुनें", "demo.book": "डेमो बुक करें", "demo.expect": "क्या होगा", "demo.quick": "सीधा और उपयोगी", "demo.quickBody": "किसी तैयारी की ज़रूरत नहीं। अपने ऑपरेशन से जुड़े सवाल साथ लाएँ।", "demo.done": "रिक्वेस्ट मिल गई", "demo.doneBody": "आपकी रिक्वेस्ट पहुँच गई है। हमारी टीम {date} को {time} की पुष्टि के लिए {email} पर संपर्क करेगी।",
    "blog.badge": "जर्नल", "blog.title": "सैलून मालिकों के लिए उपयोगी जानकारी", "blog.body": "ऑपरेशंस, क्लाइंट, टीम, स्टॉक और ग्रोथ पर व्यावहारिक गाइड।", "blog.all": "सभी", "blog.featured": "खास", "blog.read": "आर्टिकल पढ़ें", "blog.empty": "इस कैटेगरी में अभी कोई आर्टिकल नहीं है।", "blog.postMissing": "आर्टिकल नहीं मिला",
    "notFound.title": "पेज नहीं मिला", "notFound.body": "यह पेज शायद दूसरी जगह चला गया है। आगे बढ़ने के लिए नीचे दिए लिंक चुनें।", "notFound.home": "होम", "notFound.features": "फ़ीचर्स", "notFound.pricing": "प्लान", "notFound.back": "पीछे जाएँ",
    "compare.badge": "Aura क्यों", "compare.title": "Aura और दूसरे विकल्प", "compare.body": "भारतीय सैलून ऑपरेशंस के लिए व्यावहारिक तुलना।", "compare.feature": "फ़ीचर", "compare.local": "लोकल टूल", "compare.note": "Fresha ऑनलाइन बुकिंग पर कमीशन ले सकता है। Vagaro की कीमत USD में है और यह भारतीय ऑपरेशंस के अनुसार नहीं बना है।",
    "testimonials.badge": "सैलून की कहानियाँ", "testimonials.title": "सैलून टीमों को क्या पसंद है", "testimonials.body": "Aura इस्तेमाल करने वाले सैलून मालिकों और मैनेजरों के अनुभव।", "testimonials.prev": "पिछली कहानी", "testimonials.next": "अगली कहानी", "testimonials.go": "कहानी {number} पर जाएँ",
    "stats.0": "बुक किए गए अपॉइंटमेंट", "stats.1": "Aura इस्तेमाल करने वाले सैलून", "stats.2": "प्रोसेस हुए ट्रांज़ैक्शन", "stats.3": "अपटाइम प्रतिबद्धता",
    "overlay.close": "बंद करें", "overlay.email": "अपना ईमेल दर्ज करें", "overlay.noSpam": "कोई स्पैम नहीं। कभी भी अनसब्सक्राइब करें।", "overlay.whatsapp": "मदद चाहिए? हमसे चैट करें", "overlay.chat": "WhatsApp पर चैट करें", "overlay.top": "ऊपर जाएँ", "video.play": "वीडियो चलाएँ", "video.pause": "वीडियो रोकें", "video.mute": "आवाज़ बंद करें", "video.unmute": "आवाज़ चालू करें", "video.label": "Aura प्रोडक्ट वॉकथ्रू"
  }
};

export const FEATURE_MESSAGES_HI: Record<string, { title: string; subtitle: string; capabilities: { title: string; description: string }[]; stats: string[] }> = {
  appointments: { title: "स्मार्ट बुकिंग और अपॉइंटमेंट", subtitle: "ऐसी शेड्यूलिंग जो सही स्लॉट, स्टाफ और क्लाइंट को एक साथ रखे", capabilities: [
    { title: "वर्किंग कैलेंडर", description: "डे, वीक और मंथ व्यू के साथ रीशेड्यूलिंग, वॉक-इन और मल्टी-स्टाफ संदर्भ।" }, { title: "ऑनलाइन बुकिंग पोर्टल", description: "सर्विस और professional selection के साथ pay-at-salon booking।" }, { title: "स्लॉट सुझाव", description: "स्टाफ उपलब्धता, सर्विस समय और सैलून क्षमता के आधार पर practical slot।" }, { title: "वेटलिस्ट और QR चेक-इन", description: "कैलेंडर के साथ waitlist request और walk-in QR check-in।" }], stats: ["स्टाफ संदर्भ", "स्टेटस फ्लो", "ब्रांच स्कोप"] },
  billing: { title: "POS और बिलिंग", subtitle: "GST इनवॉइस, स्प्लिट पेमेंट और डेली क्लोज़िंग एक ही जगह", capabilities: [
    { title: "GST-रेडी इनवॉइस", description: "GST गणना, HSN/SAC संदर्भ और थर्मल प्रिंटिंग के साथ इनवॉइस रिकॉर्ड।" }, { title: "स्प्लिट पेमेंट", description: "एक बिल पर UPI, कार्ड, कैश, वॉलेट और गिफ्ट कार्ड का मिश्रण।" }, { title: "डेली क्लोज़िंग और Z-रिपोर्ट", description: "कैश ड्रॉअर, दिन के मिलान और अंतर की साफ़ रिपोर्ट।" }, { title: "इनवॉइस कंट्रोल", description: "होल्ड, वॉइड, रिफंड और हर बदलाव की ऑडिट हिस्ट्री।" }], stats: ["इनवॉइस रिकॉर्ड", "पेमेंट विकल्प", "इवेंट हिस्ट्री"] },
  "client-crm": { title: "Customer 360 इंटेलिजेंस", subtitle: "पहली विज़िट से लाइफटाइम वैल्यू तक हर क्लाइंट की पूरी कहानी", capabilities: [
    { title: "पूरा क्लाइंट प्रोफ़ाइल", description: "विज़िट, खरीद, पसंद, नोट्स, टैग, कंसेंट और WhatsApp हिस्ट्री।" }, { title: "वैल्यू और फॉलो-अप संदर्भ", description: "LTV, risk context और follow-up के लिए formula व configured rules।" }, { title: "लॉयल्टी और वॉलेट", description: "पॉइंट्स, डिजिटल वॉलेट, क्रेडिट नोट और स्टोर क्रेडिट।" }, { title: "क्लाइंट मेमोरी", description: "पसंद, एलर्जी और प्रोडक्ट रिएक्शन जैसी ज़रूरी जानकारी सुरक्षित रखें।" }], stats: ["विज़िट संदर्भ", "क्रेडिट रिकॉर्ड", "क्लाइंट कंट्रोल"] },
  "staff-management": { title: "Staff OS", subtitle: "अटेंडेंस से पेरोल तक पूरी टीम का संचालन", capabilities: [
    { title: "अटेंडेंस कंट्रोल", description: "फेस, बायोमेट्रिक और मैनुअल रिकॉर्ड; Staff App secure attendance policy enabled होने पर Android-only है।" }, { title: "कमीशन नियम", description: "सर्विस, प्रोडक्ट और मेंबरशिप के अनुसार attribution और permission-gated views।" }, { title: "पेरोल रिकॉर्ड", description: "अटेंडेंस, कमीशन, कटौती और पेरोल एक्सपोर्ट एक review flow में।" }, { title: "परफॉर्मेंस संदर्भ", description: "Targets, contribution और अनुमति वाले performance measures।" }], stats: ["शिफ्ट संदर्भ", "अटेंडेंस policy", "पेरोल review"] },
  inventory: { title: "Inventory Brain", subtitle: "स्टॉक, बैच, एक्सपायरी और उपयोग पर साफ़ नियंत्रण", capabilities: [
    { title: "बैच और FIFO ट्रैकिंग", description: "बैच के अनुसार स्टॉक, FIFO लागत, एक्सपायरी और वेस्टेज।" }, { title: "रीऑर्डर सुझाव", description: "पिछले उपयोग, lead time, season और आने वाली booking का review।" }, { title: "सप्लायर मैनेजमेंट", description: "वेंडर प्रोफ़ाइल, परचेज बिल और खरीद की tracking।" }, { title: "सर्विस रेसिपी", description: "सर्विस से प्रोडक्ट जोड़कर खपत और प्रति-सर्विस लागत देखें।" }], stats: ["एक्सपायरी संदर्भ", "सर्विस उपयोग", "रीऑर्डर review"] },
  "marketing-ai": { title: "मार्केटिंग वर्कफ़्लो", subtitle: "सही क्लाइंट को सही समय पर उपयोगी संदेश", capabilities: [
    { title: "बर्थडे और फेस्टिवल कैंपेन", description: "Template और rules से birthday message, festival campaign और seasonal offer तैयार करें।" }, { title: "WhatsApp वर्कफ़्लो", description: "बुकिंग confirmation, reminder, follow-up और payment reminder तैयार करें।" }, { title: "लीड मैनेजमेंट", description: "Enquiry से conversion तक lead और planned follow-up track करें।" }, { title: "कंटेंट सहायता", description: "Configured provider और उपलब्ध local fallback से caption व campaign copy draft करें।" }], stats: ["Audience rules", "Message template", "Provider disclosure"] },
  finance: { title: "Finance Engine", subtitle: "डेली क्लोज़िंग से लेजर और प्रॉफिट तक साफ़ वित्तीय तस्वीर", capabilities: [
    { title: "डेली क्लोज़िंग", description: "कैश ड्रॉअर, खर्च, payment और अंतर के साथ दिन का review।" }, { title: "बैलेंस शीट और लेजर", description: "जर्नल एंट्री, grouping और बैलेंस शीट के साथ डबल-एंट्री सिस्टम।" }, { title: "प्रॉफिट इंटेलिजेंस", description: "Formula-based cost centre, margin और profitability context।" }, { title: "GST और टैक्स रिपोर्ट", description: "GST calculation, reporting data और TDS tracking; direct filing नहीं।" }], stats: ["डेली review", "सोर्स-लिंक्ड", "ब्रांच स्कोप"] },
  compliance: { title: "स्टैच्यूटरी कंप्लायंस", subtitle: "PF, ESI, TDS और प्रोफेशनल टैक्स के लिए व्यवस्थित वर्कफ़्लो", capabilities: [
    { title: "PF और ESI रिकॉर्ड", description: "Owner या professional review के लिए calculation, deduction और payroll record।" }, { title: "TDS सेक्शन 192", description: "सैलरी TDS, declaration, proof और Form 16 workflow record।" }, { title: "प्रोफेशनल टैक्स", description: "राज्य के अनुसार professional tax calculation और deduction context।" }, { title: "कंप्लायंस कैलेंडर", description: "Due date, reminder और review status एक जगह।" }], stats: ["पेरोल संदर्भ", "Review trail", "Due date"] },
  "white-label": { title: "White Label SaaS", subtitle: "आपका ब्रांड, डोमेन और मल्टी-लोकेशन पहचान", capabilities: [
    { title: "कस्टम ब्रांडिंग", description: "पूरे प्लेटफ़ॉर्म पर आपका लोगो, रंग, फ़ॉन्ट और ब्रांड पहचान।" }, { title: "कस्टम डोमेन", description: "अपने डोमेन पर सैलून बुकिंग और पोर्टल चलाएँ।" }, { title: "मल्टी-टेनेंट आर्किटेक्चर", description: "हर टेनेंट का अलग डेटा और नियंत्रित साझा इंफ्रास्ट्रक्चर।" }, { title: "मल्टी-लोकेशन पहचान", description: "अधिकृत ब्रांच में approved branding और location context बनाए रखें।" }], stats: ["आपका ब्रांड", "कस्टम डोमेन", "टेनेंट आइसोलेशन"] }
};

export const BLOG_META_HI: Record<string, { title: string; excerpt: string; category: string; readTime: string }> = {
  "how-to-increase-salon-revenue": { title: "सैलून की आय बढ़ाने की 7 व्यावहारिक रणनीतियाँ", excerpt: "स्मार्ट प्राइसिंग, सही अपसेल और बेहतर क्लाइंट रिटेंशन से आय बढ़ाने के तरीके।", category: "बिज़नेस ग्रोथ", readTime: "8 मिनट" },
  "salon-staff-management-guide": { title: "सैलून स्टाफ मैनेजमेंट की पूरी गाइड", excerpt: "अटेंडेंस, कमीशन, परफॉर्मेंस और पेरोल को बेहतर तरीके से संभालें।", category: "स्टाफ मैनेजमेंट", readTime: "12 मिनट" },
  "digital-transformation-salon": { title: "आपके सैलून को डिजिटल बदलाव की ज़रूरत क्यों है", excerpt: "मैनुअल काम कम करके बुकिंग, बिलिंग और क्लाइंट अनुभव को जोड़ने की शुरुआत।", category: "इंडस्ट्री", readTime: "6 मिनट" },
  "gst-billing-salon-guide": { title: "सैलून के लिए GST बिलिंग: आसान गाइड", excerpt: "GST रजिस्ट्रेशन, सही इनवॉइस और रिटर्न डेटा की बुनियादी समझ।", category: "कंप्लायंस", readTime: "10 मिनट" },
  "salon-marketing-automation": { title: "सैलून मार्केटिंग ऑटोमेशन कैसे शुरू करें", excerpt: "बर्थडे, फॉलो-अप और री-एंगेजमेंट वर्कफ़्लो को उपयोगी बनाना सीखें।", category: "मार्केटिंग", readTime: "9 मिनट" },
  "salon-inventory-management": { title: "इन्वेंटरी में होने वाला नुकसान कैसे रोकें", excerpt: "बैच, FIFO, रीऑर्डर और सर्विस उपयोग से स्टॉक पर नियंत्रण रखें।", category: "ऑपरेशंस", readTime: "7 मिनट" }
};

export const BLOG_CONTENT_HI: Record<string, string> = {
  "how-to-increase-salon-revenue": `सैलून की आय सिर्फ़ ज़्यादा बुकिंग से नहीं बढ़ती। सही कीमत, बेहतर स्लॉट उपयोग और क्लाइंट को समय पर वापस लाना उतना ही ज़रूरी है।\n\n## 1. स्मार्ट प्राइसिंग अपनाएँ\n\nहर सर्विस का मार्जिन और समय देखें। धीमे घंटों में सीमित happy hours रखें, लेकिन पीक टाइम की कीमत कम न करें।\n\n## 2. उपयोगी अपसेल करें\n\nक्लाइंट की पिछली सर्विस और पसंद के आधार पर संबंधित ट्रीटमेंट या होम-केयर प्रोडक्ट सुझाएँ। सुझाव स्वाभाविक और उपयोगी होना चाहिए।\n\n## 3. नो-शो कम करें\n\nअपॉइंटमेंट से 24 घंटे और 1 घंटे पहले WhatsApp रिमाइंडर भेजें। महँगी सर्विस के लिए छोटा डिपॉज़िट उपयोगी हो सकता है।\n\n## 4. मेंबरशिप और रिटेंशन\n\nऐसी मेंबरशिप बनाएँ जिसमें priority booking और स्पष्ट फायदे हों। CRM से inactive क्लाइंट पहचानकर सही समय पर संदेश भेजें।\n\n## 5. टीम और मार्केटिंग ऑटोमेट करें\n\nपीक आवर्स के अनुसार शिफ्ट रखें और बर्थडे, फेस्टिवल व win-back कैंपेन को ऑटोमेट करें।`,
  "salon-staff-management-guide": `अच्छा स्टाफ मैनेजमेंट सिर्फ़ अटेंडेंस तक सीमित नहीं है। शिफ्ट, कमीशन, क्लाइंट रिटेंशन और पेरोल को एक साथ देखना ज़रूरी है।\n\n## भरोसेमंद अटेंडेंस\n\nबायोमेट्रिक, फेस या GPS विकल्प के साथ स्पष्ट attendance policy रखें। बदलाव और approval का रिकॉर्ड सुरक्षित रखें।\n\n## सही कमीशन संरचना\n\nसिर्फ़ कुल बिक्री नहीं, बल्कि consistency, repeat clients और service quality को भी reward करें। नियम टीम को आसानी से समझ आने चाहिए।\n\n## परफॉर्मेंस और पेरोल\n\nRevenue per stylist, client retention और service time जैसे metrics साझा करें। Attendance, commission, deduction और bonus को एक payroll workflow में जोड़ें।`,
  "digital-transformation-salon": `डिजिटल बदलाव का मतलब महँगा या जटिल सिस्टम नहीं है। इसका मतलब है मैनुअल, गलती-भरे काम को जुड़े और मापने योग्य workflow में बदलना।\n\n## कहाँ से शुरू करें\n\n- **Appointments** — फोन और रजिस्टर के साथ online booking जोड़ें\n- **Billing** — GST invoice और digital payment अपनाएँ\n- **Client CRM** — history, preference और follow-up एक जगह रखें\n- **Inventory** — stock, expiry और reorder साफ़ देखें\n- **Marketing** — birthday और re-engagement workflow बनाएँ\n\n## धीरे शुरू करें, सही तरीके से बढ़ें\n\nपहले billing और appointments जैसी बड़ी समस्या हल करें। फिर CRM, stock और multi-branch reporting जोड़ें। ऐसा सिस्टम चुनें जो UPI, GST, WhatsApp और भारतीय समय व ऑपरेशन समझता हो।`,
  "gst-billing-salon-guide": `GST नियम व्यवसाय और परिस्थिति के अनुसार बदल सकते हैं, इसलिए अपने tax advisor से पुष्टि करना ज़रूरी है। सॉफ्टवेयर का काम सही डेटा और रिकॉर्ड तैयार रखना है।\n\n## सही इनवॉइस में क्या हो\n\n- Salon GSTIN और ज़रूरत होने पर client GSTIN\n- सही SAC/HSN code\n- क्रम में invoice number और तारीख\n- Taxable value तथा CGST/SGST या IGST का स्पष्ट विभाजन\n\n## रिकॉर्ड और रिटर्न\n\nSales, payment, refund और tax adjustments का audit trail रखें। GSTR डेटा तैयार करते समय invoices और payments का reconciliation करें। Aura GST गणना और invoice records को व्यवस्थित रखता है; filing से पहले tax professional की समीक्षा लें।`,
  "salon-marketing-automation": `मार्केटिंग ऑटोमेशन का उद्देश्य ज़्यादा संदेश भेजना नहीं, बल्कि सही समय पर उपयोगी संदेश भेजना है।\n\n## तीन उपयोगी workflow\n\n### 1. Birthday और anniversary\n\nक्लाइंट को व्यक्तिगत संदेश और स्पष्ट, सीमित offer भेजें।\n\n### 2. Re-engagement\n\n45–60 दिनों से न आए क्लाइंट को हल्का reminder भेजें। बार-बार संदेश न भेजें।\n\n### 3. Visit के बाद follow-up\n\nधन्यवाद, care tips और अगली appointment का उपयोगी सुझाव भेजें।\n\n## WhatsApp का सही उपयोग\n\nConsent रखें, opt-out दें और transactional व promotional message अलग रखें। Open, redemption और retention metrics से workflow सुधारें।`,
  "salon-inventory-management": `सैलून इन्वेंटरी में expiry, overuse और गलत reorder से लगातार नुकसान हो सकता है। हर product का stock ही नहीं, उसका batch और service usage भी देखना चाहिए।\n\n## नियंत्रण की बुनियाद\n\n- **FIFO** — पुराना stock पहले इस्तेमाल करें\n- **Expiry tracking** — समय रहते alert लें\n- **Service recipes** — हर service में अनुमानित product usage तय करें\n- **Stock audit** — system और physical count का नियमित मिलान करें\n\n## Reorder point\n\nऔसत daily usage, supplier lead time और safety stock के आधार पर reorder तय करें। Multi-location salon में branch-wise stock visibility रखें, ताकि बेवजह खरीद से पहले transfer किया जा सके।`
};

export const PRICING_FEATURES_HI: string[][] = [
  ["1 ब्रांच", "अनलिमिटेड अपॉइंटमेंट", "GST POS और बिलिंग", "Client CRM", "बेसिक रिपोर्ट", "ऑनलाइन बुकिंग पोर्टल", "WhatsApp नोटिफिकेशन", "ईमेल सपोर्ट"],
  ["5 ब्रांच तक", "Starter के सभी फ़ीचर", "Staff OS: अटेंडेंस और पेरोल", "इन्वेंटरी मैनेजमेंट", "मार्केटिंग कैंपेन वर्कफ़्लो", "Finance Engine", "Customer 360 संदर्भ", "डिस्काउंट नियम और Happy Hours", "प्रायोरिटी सपोर्ट", "API एक्सेस"],
  ["अनलिमिटेड ब्रांच", "Growth के सभी फ़ीचर", "White Label ब्रांडिंग", "कस्टम डोमेन और लोगो", "PF/ESI/TDS कंप्लायंस", "फ्रैंचाइज़ मैनेजमेंट", "Digital Twin Simulator", "डेडिकेटेड अकाउंट मैनेजर", "कस्टम इंटीग्रेशन", "SLA प्रतिबद्धता"]
];

export const PRICING_FAQ_HI = [
  { question: "क्या फ्री ट्रायल मिलता है?", answer: "हाँ। हर प्लान के साथ 14 दिन का फ्री ट्रायल मिलता है और क्रेडिट कार्ड की ज़रूरत नहीं है।" },
  { question: "क्या बाद में प्लान बदल सकते हैं?", answer: "हाँ। आप ज़रूरत के अनुसार कभी भी प्लान अपग्रेड या डाउनग्रेड कर सकते हैं।" },
  { question: "मल्टी-ब्रांच प्राइसिंग कैसे काम करती है?", answer: "Starter एक ब्रांच के लिए है, Growth में 5 ब्रांच तक और Enterprise में कस्टम मल्टी-ब्रांच प्राइसिंग मिलती है।" },
  { question: "क्या वार्षिक भुगतान पर छूट है?", answer: "हाँ। वार्षिक बिलिंग मासिक बिलिंग की तुलना में 20% बचत देती है।" },
  { question: "कौन से पेमेंट तरीके स्वीकार हैं?", answer: "UPI, क्रेडिट या डेबिट कार्ड, नेट बैंकिंग और बैंक ट्रांसफर स्वीकार हैं।" },
  { question: "क्या मेरा डेटा सुरक्षित है?", answer: "Aura tenant isolation, role-based access, audit trail और नियमित backup controls का उपयोग करता है।" }
];

export const PRICING_COMPARISON_HI = ["ब्रांच", "अपॉइंटमेंट", "GST POS और बिलिंग", "Client CRM", "ऑनलाइन बुकिंग पोर्टल", "WhatsApp नोटिफिकेशन", "बेसिक रिपोर्ट", "Staff OS: अटेंडेंस और पेरोल", "इन्वेंटरी मैनेजमेंट", "मार्केटिंग कैंपेन वर्कफ़्लो", "Finance Engine", "Customer 360 संदर्भ", "डिस्काउंट नियम और Happy Hours", "API एक्सेस", "White Label ब्रांडिंग", "कस्टम डोमेन और लोगो", "PF/ESI/TDS कंप्लायंस", "फ्रैंचाइज़ मैनेजमेंट", "डेडिकेटेड अकाउंट मैनेजर", "कस्टम इंटीग्रेशन"];

export const FEATURE_OVERVIEW_HI = [
  { title: "स्मार्ट बुकिंग", description: "स्मार्ट स्लॉट सुझाव, ऑनलाइन बुकिंग, वेटलिस्ट और QR चेक-इन।" },
  { title: "POS और बिलिंग", description: "GST इनवॉइस, UPI/कार्ड/कैश/वॉलेट स्प्लिट पेमेंट और डेली क्लोज़िंग।" },
  { title: "Customer 360", description: "क्लाइंट हिस्ट्री, लॉयल्टी, वॉलेट, WhatsApp और उपयोगी इनसाइट।" },
  { title: "Staff OS", description: "अटेंडेंस, शिफ्ट, कमीशन, पेरोल और परफॉर्मेंस।" },
  { title: "Inventory Brain", description: "बैच, FIFO, एक्सपायरी, रीऑर्डर, सप्लायर और वेस्टेज।" },
  { title: "मार्केटिंग वर्कफ़्लो", description: "बर्थडे कैंपेन, WhatsApp sequence, lead follow-up और performance tracking।" },
  { title: "Finance Engine", description: "डेली क्लोज़िंग, खर्च, लेजर, बैलेंस शीट और प्रॉफिट इंटेलिजेंस।" },
  { title: "कंप्लायंस", description: "PF, ESI, TDS, प्रोफेशनल टैक्स और पेरोल वर्कफ़्लो।" },
  { title: "White Label", description: "मल्टी-लोकेशन सैलून और फ्रैंचाइज़ के लिए कस्टम ब्रांड, डोमेन और लोगो।" }
];

export const TESTIMONIALS_HI = [
  { quote: "Aura ने हमारे सैलून का काम पूरी तरह डिजिटल कर दिया। अपॉइंटमेंट, क्लाइंट हिस्ट्री और बिलिंग अब एक ही जगह संभलते हैं।", role: "मालिक" },
  { quote: "अटेंडेंस, पेरोल और कमीशन एक साथ आने से हर हफ़्ते का प्रशासनिक काम बहुत कम हुआ है।", role: "डायरेक्टर" },
  { quote: "Customer 360 से हर क्लाइंट की पसंद और पुरानी सर्विस तुरंत दिखती है। टीम अब ज़्यादा व्यक्तिगत अनुभव दे पाती है।", role: "मैनेजर" },
  { quote: "GST बिलिंग, UPI और WhatsApp का भारतीय ऑपरेशन के अनुसार जुड़ना हमारे लिए सबसे उपयोगी है।", role: "मालिक" },
  { quote: "बर्थडे, फॉलो-अप और re-engagement workflow अपने आप चलते हैं, इसलिए टीम क्लाइंट पर ध्यान दे पाती है।", role: "मालिक" },
  { quote: "कई ब्रांच का रियल-टाइम डेटा एक जगह दिखने से रोज़ के फैसले और तुलना बहुत आसान हुई है।", role: "CEO" }
];

export const CASE_STUDIES_HI = [
  { quote: "Aura के बाद बुकिंग, क्लाइंट follow-up और मार्केटिंग एक ही workflow में आ गए।", labels: ["मासिक आय", "एक्टिव क्लाइंट", "टीम साइज़", "नो-शो"] },
  { quote: "Staff OS ने अटेंडेंस, कमीशन और पेरोल के मैनुअल काम को काफी कम किया।", labels: ["मासिक आय", "एक्टिव क्लाइंट", "टीम साइज़", "नो-शो"] }
];

export const ABOUT_VALUES_HI = [
  { title: "सैलून-फर्स्ट", description: "हर फ़ीचर असली सैलून ऑपरेशन के लिए बनाया गया है, सामान्य बिज़नेस जरूरतों के लिए नहीं।" },
  { title: "सरलता", description: "शक्तिशाली सॉफ्टवेयर जटिल होना ज़रूरी नहीं। मुश्किल काम को आसान बनाना हमारी प्राथमिकता है।" },
  { title: "भारतीय बाज़ार", description: "GST, UPI, WhatsApp, भारतीय पेरोल और IST workflow के अनुसार।" },
  { title: "AI सहायता", description: "ऐसा ऑटोमेशन जो आपके डेटा से उपयोगी संदर्भ लेकर रोज़ के फैसलों में मदद करे।" }
];

export const ABOUT_TIMELINE_HI = [
  { title: "जुड़ा हुआ कोर", description: "अपॉइंटमेंट, Client CRM, POS और स्टॉक एक ऑपरेशनल संदर्भ साझा करते हैं।" },
  { title: "इंटेलिजेंट ऑपरेशंस", description: "स्टाफ, मार्केटिंग, इन्वेंटरी और फाइनेंस में केंद्रित ऑटोमेशन जुड़ता है।" },
  { title: "मल्टी-लोकेशन नींव", description: "टेनेंट आइसोलेशन और ब्रांच-आधारित एक्सेस अधिकृत ऑपरेशन संभालते हैं।" },
  { title: "प्रमाण-आधारित रोलआउट", description: "असली प्रोडक्ट मीडिया और ग्राहक प्रमाण मंज़ूरी के बाद ही प्रकाशित होंगे।" }
];

export const DEMO_BENEFITS_HI = ["15 मिनट का पर्सनल वॉकथ्रू", "आपके सैलून साइज़ के अनुसार फ़ीचर", "अपने सवालों के सीधे जवाब", "सेटअप और माइग्रेशन पर स्पष्ट मार्गदर्शन"];

export const HOME_COMPARISON_HI = ["GST-रेडी बिलिंग", "UPI पेमेंट", "WhatsApp इंटीग्रेशन", "AI मार्केटिंग ऑटोमेशन", "भारतीय पेरोल: PF/ESI", "मल्टी-ब्रांच डैशबोर्ड", "ऑनलाइन बुकिंग पोर्टल", "Client CRM और 360 व्यू", "इन्वेंटरी मैनेजमेंट", "शुरुआती कीमत", "भारतीय बाज़ार के लिए सपोर्ट"];

export const EXPERIENCE_MESSAGES: Record<"en" | "hi", Record<string, string>> = {
  en: {
    "business.label": "Tailor this page to", "business.salon": "Salon", "business.spa": "Spa", "business.nail": "Nail & beauty studio", "business.bridal": "Bridal studio", "business.multi": "Multi-branch",
    "business.salon.hero": "Appointments, client history, checkout, staff and stock stay connected from reception to closing.",
    "business.spa.hero": "Coordinate treatment rooms, longer services, client preferences, packages and follow-ups in one workflow.",
    "business.nail.hero": "Keep quick bookings, repeat preferences, retail products and artist schedules easy to see and act on.",
    "business.bridal.hero": "Bring consultations, multi-service bookings, deposits, client notes and follow-ups into one timeline.",
    "business.multi.hero": "Give each branch a focused workspace while owners retain branch-aware controls and reporting.",
    "tour.badge": "Product tour", "tour.title": "Follow the work, not a fake dashboard", "tour.body": "These handcrafted views are based on confirmed Aura workflows. They illustrate the product structure and are not a live customer account.", "tour.sample": "Illustrative product view", "tour.replace": "Prepared for real product media", "tour.prev": "Previous workflow", "tour.next": "Next workflow",
    "tour.appointments": "Appointments", "tour.appointments.body": "Staff lanes, service duration, status, chairs, waitlist and booking actions share the same calendar context.",
    "tour.customer": "Customer 360", "tour.customer.body": "Visit history, preferences, wallet, loyalty, risk context and next actions stay attached to the client.",
    "tour.pos": "POS & checkout", "tour.pos.body": "Services and products flow into GST-ready billing with UPI, cash, card and wallet split payments.",
    "tour.staff": "Staff operations", "tour.staff.body": "Attendance, shifts, commissions, incentives and payroll exports use the same operational records.",
    "tour.inventory": "Inventory", "tour.inventory.body": "Products, suppliers, batches, expiry, service recipes, usage and reorder guidance remain connected.",
    "tour.finance": "Finance", "tour.finance.body": "Cash drawer, daily closing, expenses, payments, refunds and ledger workflows preserve an audit trail.",
    "tour.branches": "Multi-branch", "tour.branches.body": "Branch context scopes bookings, staff, inventory and reporting while owners can compare authorised locations.",
    "tour.calendar": "Staff calendar", "tour.waitlist": "Waitlist", "tour.arrived": "Arrived", "tour.confirmed": "Confirmed", "tour.clientMemory": "Client memory", "tour.preference": "Preference", "tour.history": "Visit timeline", "tour.nextAction": "Next best action", "tour.bill": "Current bill", "tour.subtotal": "Subtotal", "tour.gst": "GST", "tour.payment": "Payment split", "tour.shift": "Today’s shift", "tour.commission": "Commission policy", "tour.attendance": "Attendance", "tour.stock": "Stock control", "tour.batch": "Batch & expiry", "tour.recipe": "Service recipe", "tour.reorder": "Reorder review", "tour.closing": "Daily closing", "tour.drawer": "Cash drawer", "tour.expenses": "Expenses", "tour.ledger": "Ledger trail", "tour.branchContext": "Branch context", "tour.switchBranch": "Switch branch", "tour.compareBranches": "Compare authorised branches",
    "tour.time": "Time", "tour.hairColour": "Hair colour", "tour.facial": "Facial", "tour.hairSpa": "Hair spa", "tour.minute": "min", "tour.chair": "Chair", "tour.member": "Member", "tour.eveningSlots": "evening slots", "tour.reviewColour": "Review colour notes", "tour.completedInvoice": "Completed · invoice linked", "tour.consultation": "Consultation note", "tour.preferenceUpdated": "Preference updated", "tour.membership": "Membership", "tour.redemption": "Redemption recorded", "tour.careProduct": "Care product", "tour.checkoutCalc": "Calculated at checkout", "tour.card": "Card", "tour.balance": "Balance", "tour.paymentAudit": "GST invoice · payment records · audit history", "tour.attendanceModes": "Face / biometric / manual", "tour.commissionSources": "Service · product · membership", "tour.payroll": "Payroll", "tour.payrollExport": "Attendance + commission export", "tour.shiftPlanning": "Shift planning", "tour.incentive": "Incentive calculation", "tour.performance": "Performance context", "tour.batchDetails": "Batch code · expiry · supplier", "tour.productUsage": "Product usage per service", "tour.usageLead": "Usage + lead time context", "tour.purchaseEntry": "Purchase entry", "tour.wasteRecord": "Waste record", "tour.stockAudit": "Stock audit", "tour.drawerFlow": "Open · payments · variance", "tour.expenseContext": "Category · branch · record", "tour.sourceJournal": "Source-linked journal entries", "tour.partialPayments": "Partial payments", "tour.refunds": "Refunds", "tour.staffPayouts": "Staff payouts", "tour.authorisedScope": "Authorised branch scope", "tour.bookingsStaff": "Bookings & staff", "tour.branchAware": "Branch-aware operations", "tour.inventoryReports": "Inventory & reports", "tour.scopedRecords": "Scoped records", "tour.tenantIsolation": "Tenant isolation", "tour.branchBranding": "Branch branding",
    "roi.badge": "Estimate with your numbers", "roi.title": "Build a transparent ROI scenario", "roi.body": "Change every assumption yourself. Aura does not guarantee recovered revenue or time savings.", "roi.appointments": "Monthly appointments", "roi.ticket": "Average ticket (₹)", "roi.noShow": "Current no-show rate (%)", "roi.recovery": "No-shows you believe you can recover (%)", "roi.hours": "Admin hours you expect to save monthly", "roi.hourValue": "Value of one admin hour (₹)", "roi.monthly": "Estimated monthly opportunity", "roi.annual": "Annualised scenario", "roi.revenue": "Potential recovered appointment value", "roi.time": "Estimated admin-time value", "roi.method": "Show calculation method", "roi.formulaRevenue": "Appointments × average ticket × no-show rate × your recovery assumption", "roi.formulaTime": "Admin hours saved × value per hour", "roi.disclaimer": "Illustrative estimate only. Actual results depend on adoption, workflows, demand and team execution.", "roi.cta": "Review this scenario in a demo",
    "advisor.badge": "Plan advisor", "advisor.title": "Match the plan to your operation", "advisor.body": "Answer three practical questions. The recommendation uses only the published branch limits and capabilities below.", "advisor.branches": "Number of branches", "advisor.team": "Team size", "advisor.needs": "Capabilities you need", "advisor.staff": "Staff OS and payroll", "advisor.inventory": "Inventory management", "advisor.marketing": "Marketing workflows", "advisor.finance": "Finance Engine", "advisor.api": "API access", "advisor.whiteLabel": "White Label branding", "advisor.compliance": "PF/ESI/TDS record workflows", "advisor.recommendation": "Recommended starting plan", "advisor.why": "Why", "advisor.starterWhy": "One branch and no selected advanced capability fit Starter’s published scope.", "advisor.growthWhy": "Up to five branches or the selected operational capabilities fit Growth’s published scope.", "advisor.enterpriseWhy": "More than five branches, White Label or statutory record workflows fit Enterprise’s published scope.", "advisor.teamNote": "Team size is collected for demo context only; the current plan data does not publish team-seat limits.", "advisor.from": "From", "advisor.demo": "Discuss this plan", "advisor.contact": "Contact sales",
    "foundation.badge": "Confirmed product foundations", "foundation.title": "Built for operational integrity", "foundation.tenant": "Tenant isolation", "foundation.tenant.body": "Tenant-owned data and access remain scoped to the salon organisation.", "foundation.branch": "Branch-aware records", "foundation.branch.body": "Bookings, staff, stock and reports respect authorised branch context.", "foundation.realtime": "Real-time events", "foundation.realtime.body": "Booking, dashboard, queue and notification changes can flow through the realtime layer.", "foundation.dates": "IST business dates", "foundation.dates.body": "Operational dates and daily workflows follow Indian business time.",
    "proof.badge": "Evidence, not decoration", "proof.title": "A home for customer-approved proof", "proof.body": "We will publish real product media and customer voices only after approval. These prepared slots make that future update direct and honest.", "proof.workflow": "Product workflow", "proof.workflow.body": "An approved screen recording showing one complete task, with account data removed.", "proof.voice": "Customer voice", "proof.voice.body": "A named quote, role, salon and city supplied with explicit publication permission.", "proof.permission": "Evidence record", "proof.permission.body": "Source, date, permission status and any measurable result documented before publication.", "proof.pending": "Awaiting approved real asset",
    "customerProof.title": "Customer evidence, published with permission", "customerProof.body": "No anonymous names, invented quotes or unsupported outcomes. This page is structured for real stories when customers approve them.", "customerProof.identity": "Named source", "customerProof.identity.body": "Customer name, role, salon and city verified before publication.", "customerProof.workflow": "Specific workflow", "customerProof.workflow.body": "The exact task and Aura module shown instead of a vague endorsement.", "customerProof.outcome": "Documented outcome", "customerProof.outcome.body": "Any number includes its period, baseline, method and customer confirmation.", "customerProof.permission": "Publication consent", "customerProof.permission.body": "Quote, logo and media permissions recorded separately.", "customerProof.workflowTitle": "Case-study slots built around real work", "customerProof.workflowBody": "Each future story has a defined workflow to demonstrate and a clear evidence requirement.", "customerProof.appointments": "Calendar setup, booking flow, waitlist and status handoff.", "customerProof.customer": "Client history, preference capture and follow-up context.", "customerProof.pos": "Service-to-invoice flow, GST and payment handling.", "customerProof.inventory": "Purchase, batch, service usage and reorder workflow.",
    "demo.sending": "Sending request...", "demo.error": "We could not send your request. Your entries are still here—please try again or contact us directly.", "demo.deliveryMissing": "Demo delivery is not configured yet. Please email hello@aurasalon.in while RESEND_API_KEY and CONTACT_EMAIL are configured.", "demo.messageIntro": "Demo request", "demo.messageSize": "Team size", "demo.messageDate": "Preferred date", "demo.messageTime": "Preferred time", "demo.messageBusiness": "Business type"
  },
  hi: {
    "business.label": "इस पेज को अपने काम के अनुसार देखें", "business.salon": "सैलून", "business.spa": "स्पा", "business.nail": "नेल और ब्यूटी स्टूडियो", "business.bridal": "ब्राइडल स्टूडियो", "business.multi": "मल्टी-ब्रांच",
    "business.salon.hero": "रिसेप्शन से डेली क्लोज़िंग तक अपॉइंटमेंट, क्लाइंट हिस्ट्री, चेकआउट, स्टाफ और स्टॉक जुड़े रहें।",
    "business.spa.hero": "ट्रीटमेंट रूम, लंबी सर्विस, क्लाइंट पसंद, पैकेज और फॉलो-अप एक वर्कफ़्लो में संभालें।",
    "business.nail.hero": "क्विक बुकिंग, रिपीट पसंद, रिटेल प्रोडक्ट और आर्टिस्ट शेड्यूल साफ़ और आसान रखें।",
    "business.bridal.hero": "कंसल्टेशन, मल्टी-सर्विस बुकिंग, डिपॉज़िट, क्लाइंट नोट्स और फॉलो-अप एक टाइमलाइन में रखें।",
    "business.multi.hero": "हर ब्रांच को केंद्रित वर्कस्पेस दें और मालिक को ब्रांच के अनुसार कंट्रोल व रिपोर्टिंग मिले।",
    "tour.badge": "प्रोडक्ट टूर", "tour.title": "असली वर्कफ़्लो देखें, नकली डैशबोर्ड नहीं", "tour.body": "ये handcrafted views Aura के पक्के वर्कफ़्लो पर आधारित हैं। ये प्रोडक्ट की संरचना दिखाते हैं, किसी लाइव ग्राहक अकाउंट को नहीं।", "tour.sample": "उदाहरण प्रोडक्ट व्यू", "tour.replace": "असली प्रोडक्ट मीडिया के लिए तैयार", "tour.prev": "पिछला वर्कफ़्लो", "tour.next": "अगला वर्कफ़्लो",
    "tour.appointments": "अपॉइंटमेंट", "tour.appointments.body": "स्टाफ लेन, सर्विस समय, स्टेटस, चेयर, वेटलिस्ट और बुकिंग एक ही कैलेंडर संदर्भ में रहें।",
    "tour.customer": "Customer 360", "tour.customer.body": "विज़िट हिस्ट्री, पसंद, वॉलेट, लॉयल्टी, रिस्क संदर्भ और अगली कार्रवाई क्लाइंट के साथ जुड़ी रहे।",
    "tour.pos": "POS और चेकआउट", "tour.pos.body": "सर्विस और प्रोडक्ट GST-रेडी बिलिंग में आएँ, जहाँ UPI, कैश, कार्ड और वॉलेट स्प्लिट पेमेंट हो।",
    "tour.staff": "स्टाफ ऑपरेशंस", "tour.staff.body": "अटेंडेंस, शिफ्ट, कमीशन, इंसेंटिव और पेरोल एक्सपोर्ट एक ही ऑपरेशनल रिकॉर्ड से चलें।",
    "tour.inventory": "इन्वेंटरी", "tour.inventory.body": "प्रोडक्ट, सप्लायर, बैच, एक्सपायरी, सर्विस रेसिपी, उपयोग और रीऑर्डर सुझाव जुड़े रहें।",
    "tour.finance": "फाइनेंस", "tour.finance.body": "कैश ड्रॉअर, डेली क्लोज़िंग, खर्च, पेमेंट, रिफंड और लेजर का ऑडिट ट्रेल बना रहे।",
    "tour.branches": "मल्टी-ब्रांच", "tour.branches.body": "ब्रांच संदर्भ बुकिंग, स्टाफ, इन्वेंटरी और रिपोर्ट को सीमित रखे; मालिक अधिकृत लोकेशन की तुलना कर सके।",
    "tour.calendar": "स्टाफ कैलेंडर", "tour.waitlist": "वेटलिस्ट", "tour.arrived": "आ चुके", "tour.confirmed": "कन्फर्म", "tour.clientMemory": "क्लाइंट मेमोरी", "tour.preference": "पसंद", "tour.history": "विज़िट टाइमलाइन", "tour.nextAction": "अगली सही कार्रवाई", "tour.bill": "मौजूदा बिल", "tour.subtotal": "सबटोटल", "tour.gst": "GST", "tour.payment": "स्प्लिट पेमेंट", "tour.shift": "आज की शिफ्ट", "tour.commission": "कमीशन नीति", "tour.attendance": "अटेंडेंस", "tour.stock": "स्टॉक कंट्रोल", "tour.batch": "बैच और एक्सपायरी", "tour.recipe": "सर्विस रेसिपी", "tour.reorder": "रीऑर्डर रिव्यू", "tour.closing": "डेली क्लोज़िंग", "tour.drawer": "कैश ड्रॉअर", "tour.expenses": "खर्च", "tour.ledger": "लेजर ट्रेल", "tour.branchContext": "ब्रांच संदर्भ", "tour.switchBranch": "ब्रांच बदलें", "tour.compareBranches": "अधिकृत ब्रांच की तुलना",
    "tour.time": "समय", "tour.hairColour": "हेयर कलर", "tour.facial": "फेशियल", "tour.hairSpa": "हेयर स्पा", "tour.minute": "मिनट", "tour.chair": "चेयर", "tour.member": "मेंबर", "tour.eveningSlots": "शाम के स्लॉट", "tour.reviewColour": "कलर नोट्स देखें", "tour.completedInvoice": "पूरा · इनवॉइस लिंक्ड", "tour.consultation": "कंसल्टेशन नोट", "tour.preferenceUpdated": "पसंद अपडेट हुई", "tour.membership": "मेंबरशिप", "tour.redemption": "रिडेम्पशन दर्ज", "tour.careProduct": "केयर प्रोडक्ट", "tour.checkoutCalc": "चेकआउट पर गणना", "tour.card": "कार्ड", "tour.balance": "बाकी राशि", "tour.paymentAudit": "GST इनवॉइस · पेमेंट रिकॉर्ड · ऑडिट हिस्ट्री", "tour.attendanceModes": "फेस / बायोमेट्रिक / मैनुअल", "tour.commissionSources": "सर्विस · प्रोडक्ट · मेंबरशिप", "tour.payroll": "पेरोल", "tour.payrollExport": "अटेंडेंस + कमीशन एक्सपोर्ट", "tour.shiftPlanning": "शिफ्ट प्लानिंग", "tour.incentive": "इंसेंटिव गणना", "tour.performance": "परफॉर्मेंस संदर्भ", "tour.batchDetails": "बैच कोड · एक्सपायरी · सप्लायर", "tour.productUsage": "हर सर्विस में प्रोडक्ट उपयोग", "tour.usageLead": "उपयोग + लीड टाइम संदर्भ", "tour.purchaseEntry": "खरीद एंट्री", "tour.wasteRecord": "वेस्ट रिकॉर्ड", "tour.stockAudit": "स्टॉक ऑडिट", "tour.drawerFlow": "ओपन · पेमेंट · अंतर", "tour.expenseContext": "कैटेगरी · ब्रांच · रिकॉर्ड", "tour.sourceJournal": "सोर्स-लिंक्ड जर्नल एंट्री", "tour.partialPayments": "आंशिक पेमेंट", "tour.refunds": "रिफंड", "tour.staffPayouts": "स्टाफ पेआउट", "tour.authorisedScope": "अधिकृत ब्रांच दायरा", "tour.bookingsStaff": "बुकिंग और स्टाफ", "tour.branchAware": "ब्रांच-आधारित ऑपरेशन", "tour.inventoryReports": "इन्वेंटरी और रिपोर्ट", "tour.scopedRecords": "दायरे के रिकॉर्ड", "tour.tenantIsolation": "टेनेंट आइसोलेशन", "tour.branchBranding": "ब्रांच ब्रांडिंग",
    "roi.badge": "अपने आंकड़ों से अनुमान", "roi.title": "पारदर्शी ROI परिदृश्य बनाएँ", "roi.body": "हर अनुमान आप खुद बदलें। Aura आय वापस मिलने या समय बचने की गारंटी नहीं देता।", "roi.appointments": "मासिक अपॉइंटमेंट", "roi.ticket": "औसत टिकट (₹)", "roi.noShow": "मौजूदा नो-शो दर (%)", "roi.recovery": "आपके अनुसार वापस मिल सकने वाले नो-शो (%)", "roi.hours": "हर महीने बचने वाले अनुमानित एडमिन घंटे", "roi.hourValue": "एक एडमिन घंटे का मूल्य (₹)", "roi.monthly": "अनुमानित मासिक अवसर", "roi.annual": "सालाना परिदृश्य", "roi.revenue": "संभावित वापस मिली अपॉइंटमेंट वैल्यू", "roi.time": "अनुमानित एडमिन समय का मूल्य", "roi.method": "गणना का तरीका देखें", "roi.formulaRevenue": "अपॉइंटमेंट × औसत टिकट × नो-शो दर × आपका रिकवरी अनुमान", "roi.formulaTime": "बचे एडमिन घंटे × प्रति घंटे का मूल्य", "roi.disclaimer": "यह केवल उदाहरण अनुमान है। असली नतीजे अपनाने, वर्कफ़्लो, मांग और टीम के काम पर निर्भर हैं।", "roi.cta": "इस परिदृश्य पर डेमो में बात करें",
    "advisor.badge": "प्लान सलाह", "advisor.title": "अपने ऑपरेशन के अनुसार प्लान चुनें", "advisor.body": "तीन आसान सवालों का जवाब दें। सलाह केवल नीचे दिए प्रकाशित ब्रांच लिमिट और फ़ीचर पर आधारित है।", "advisor.branches": "ब्रांच की संख्या", "advisor.team": "टीम साइज़", "advisor.needs": "ज़रूरी क्षमताएँ", "advisor.staff": "Staff OS और पेरोल", "advisor.inventory": "इन्वेंटरी मैनेजमेंट", "advisor.marketing": "मार्केटिंग वर्कफ़्लो", "advisor.finance": "Finance Engine", "advisor.api": "API एक्सेस", "advisor.whiteLabel": "White Label ब्रांडिंग", "advisor.compliance": "PF/ESI/TDS रिकॉर्ड वर्कफ़्लो", "advisor.recommendation": "शुरुआती सुझाया प्लान", "advisor.why": "क्यों", "advisor.starterWhy": "एक ब्रांच और कोई चुना advanced फ़ीचर नहीं होने पर Starter की प्रकाशित सीमा सही बैठती है।", "advisor.growthWhy": "पाँच ब्रांच तक या चुनी गई ऑपरेशनल क्षमताएँ Growth की प्रकाशित सीमा में आती हैं।", "advisor.enterpriseWhy": "पाँच से ज़्यादा ब्रांच, White Label या statutory रिकॉर्ड वर्कफ़्लो Enterprise की सीमा में आते हैं।", "advisor.teamNote": "टीम साइज़ केवल डेमो संदर्भ के लिए है; मौजूदा प्लान डेटा में टीम सीट लिमिट प्रकाशित नहीं है।", "advisor.from": "शुरुआत", "advisor.demo": "इस प्लान पर बात करें", "advisor.contact": "सेल्स से संपर्क करें",
    "foundation.badge": "पक्की प्रोडक्ट नींव", "foundation.title": "ऑपरेशनल भरोसे के लिए बनाया गया", "foundation.tenant": "टेनेंट आइसोलेशन", "foundation.tenant.body": "सैलून संगठन का डेटा और एक्सेस उसी टेनेंट तक सीमित रहता है।", "foundation.branch": "ब्रांच के अनुसार रिकॉर्ड", "foundation.branch.body": "बुकिंग, स्टाफ, स्टॉक और रिपोर्ट अधिकृत ब्रांच संदर्भ का पालन करते हैं।", "foundation.realtime": "रियल-टाइम इवेंट", "foundation.realtime.body": "बुकिंग, डैशबोर्ड, कतार और नोटिफिकेशन बदलाव realtime layer से जुड़ सकते हैं।", "foundation.dates": "IST बिज़नेस डेट", "foundation.dates.body": "ऑपरेशनल तारीख और डेली वर्कफ़्लो भारतीय बिज़नेस समय का पालन करते हैं।",
    "proof.badge": "सजावट नहीं, प्रमाण", "proof.title": "ग्राहक से मंज़ूर प्रमाण के लिए तैयार जगह", "proof.body": "असली प्रोडक्ट मीडिया और ग्राहक की बात मंज़ूरी के बाद ही प्रकाशित होगी। ये तैयार स्लॉट आगे का अपडेट सीधा और ईमानदार बनाते हैं।", "proof.workflow": "प्रोडक्ट वर्कफ़्लो", "proof.workflow.body": "अकाउंट डेटा हटाकर एक पूरा काम दिखाने वाली मंज़ूर स्क्रीन रिकॉर्डिंग।", "proof.voice": "ग्राहक की आवाज़", "proof.voice.body": "स्पष्ट प्रकाशन अनुमति के साथ नाम, भूमिका, सैलून और शहर वाली बात।", "proof.permission": "प्रमाण रिकॉर्ड", "proof.permission.body": "प्रकाशन से पहले स्रोत, तारीख, अनुमति स्थिति और किसी भी नतीजे का रिकॉर्ड।", "proof.pending": "मंज़ूर असली एसेट की प्रतीक्षा",
    "customerProof.title": "ग्राहक प्रमाण, पूरी अनुमति के साथ", "customerProof.body": "कोई गुमनाम नाम, बनाई हुई बात या बिना आधार का नतीजा नहीं। ग्राहक की मंज़ूरी मिलने पर यह पेज असली कहानियों के लिए तैयार है।", "customerProof.identity": "पहचाना स्रोत", "customerProof.identity.body": "प्रकाशन से पहले ग्राहक का नाम, भूमिका, सैलून और शहर सत्यापित हो।", "customerProof.workflow": "स्पष्ट वर्कफ़्लो", "customerProof.workflow.body": "सामान्य प्रशंसा के बजाय असली काम और Aura मॉड्यूल दिखे।", "customerProof.outcome": "दर्ज नतीजा", "customerProof.outcome.body": "हर संख्या के साथ अवधि, baseline, तरीका और ग्राहक पुष्टि हो।", "customerProof.permission": "प्रकाशन सहमति", "customerProof.permission.body": "Quote, logo और media की अनुमति अलग से दर्ज हो।", "customerProof.workflowTitle": "असली काम पर बने केस-स्टडी स्लॉट", "customerProof.workflowBody": "हर आने वाली कहानी के लिए दिखाने वाला वर्कफ़्लो और प्रमाण की जरूरत साफ़ है।", "customerProof.appointments": "कैलेंडर सेटअप, बुकिंग फ्लो, वेटलिस्ट और स्टेटस हैंडऑफ़।", "customerProof.customer": "क्लाइंट हिस्ट्री, पसंद और फॉलो-अप संदर्भ।", "customerProof.pos": "सर्विस से इनवॉइस, GST और पेमेंट का फ्लो।", "customerProof.inventory": "खरीद, बैच, सर्विस उपयोग और रीऑर्डर वर्कफ़्लो।",
    "demo.sending": "रिक्वेस्ट भेजी जा रही है...", "demo.error": "रिक्वेस्ट नहीं भेजी जा सकी। आपकी जानकारी सुरक्षित है—फिर कोशिश करें या सीधे संपर्क करें।", "demo.deliveryMissing": "डेमो डिलीवरी अभी कॉन्फ़िगर नहीं है। RESEND_API_KEY और CONTACT_EMAIL सेट होने तक hello@aurasalon.in पर ईमेल करें।", "demo.messageIntro": "डेमो रिक्वेस्ट", "demo.messageSize": "टीम साइज़", "demo.messageDate": "पसंदीदा तारीख", "demo.messageTime": "पसंदीदा समय", "demo.messageBusiness": "बिज़नेस प्रकार"
  }
};
