import { Container } from "@/components/ui/Container";
import { CALCULATORS } from "@/lib/authority-assets";
import { SITE_URL } from "@/lib/site";
import { CalculatorClient } from "../CalculatorClient";
import { TrustSignals } from "@/components/seo/TrustSignals";
import Link from "next/link";
import { Breadcrumbs, breadcrumbJsonLdFromCrumbs } from "@/components/seo/Breadcrumbs";

export function generateStaticParams() { return CALCULATORS.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = CALCULATORS.find((entry) => entry.slug === slug); return { title: item?.title ?? "Salon Calculator", description: `Use this ${item?.title ?? "salon calculator"} to plan salon operations.`, alternates: { canonical: `${SITE_URL}/calculators/${slug}` } }; }
export default async function CalculatorPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = CALCULATORS.find((entry) => entry.slug === slug) ?? CALCULATORS[0]; const crumbs = [{ name: "Home", href: "/" }, { name: "Calculators", href: "/calculators" }, { name: item.title, href: `/calculators/${slug}` }]; const jsonLd = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: item.title, applicationCategory: "BusinessApplication", operatingSystem: "Web" }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLdFromCrumbs(crumbs)) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="bg-[var(--aura-off-white)] py-28"><Container size="narrow"><Breadcrumbs crumbs={crumbs} /><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--aura-purple)]">Calculator</p><h1 className="mt-4 text-4xl font-bold tracking-[-0.04em]">{item.title}</h1><p className="mt-5 text-[var(--aura-body)]">Inputs: {item.inputs.join(", ")}. Formula: {item.formula}. Use this as a planning guide, then track real values inside Aura.</p><TrustSignals /><CalculatorClient slug={slug} /><div className="mt-8 rounded-3xl bg-white p-6 shadow-[var(--aura-shadow-sm)]"><h2 className="font-bold">Related tools</h2><div className="mt-3 flex flex-wrap gap-2">{CALCULATORS.filter((entry) => entry.slug !== slug).slice(0,3).map((entry) => <Link key={entry.slug} href={`/calculators/${entry.slug}`} className="rounded-full border border-[var(--aura-border)] px-3 py-1 text-xs font-semibold">{entry.title}</Link>)}</div></div><div className="mt-8 rounded-3xl bg-white p-6 shadow-[var(--aura-shadow-sm)]"><h2 className="font-bold">How to use it</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-[var(--aura-body)]"><li>Enter your current salon numbers.</li><li>Compare the result with last month.</li><li>Use Aura reports to replace estimates with actuals.</li></ol></div></Container></section></>; }
