import { Container } from "@/components/ui/Container";
import { TEMPLATES } from "@/lib/authority-assets";
import { TemplateChecklist } from "../TemplateChecklist";
import { TrustSignals } from "@/components/seo/TrustSignals";
import Link from "next/link";
import { Breadcrumbs, breadcrumbJsonLdFromCrumbs } from "@/components/seo/Breadcrumbs";

export function generateStaticParams() { return TEMPLATES.map((item) => ({ slug: item.slug })); }
export default async function TemplatePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = TEMPLATES.find((entry) => entry.slug === slug) ?? TEMPLATES[0]; const crumbs = [{ name: "Home", href: "/" }, { name: "Templates", href: "/templates" }, { name: item.title, href: `/templates/${slug}` }]; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLdFromCrumbs(crumbs)) }} /><section className="bg-[var(--aura-off-white)] py-28"><Container size="narrow"><Breadcrumbs crumbs={crumbs} /><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--aura-purple)]">Template</p><h1 className="mt-4 text-4xl font-bold tracking-[-0.04em]">{item.title}</h1><TrustSignals /><TemplateChecklist slug={slug} /><div className="mt-8 rounded-3xl bg-white p-6"><h2 className="font-bold">Related templates</h2><div className="mt-3 flex flex-wrap gap-2">{TEMPLATES.filter((entry) => entry.slug !== slug).slice(0,3).map((entry) => <Link key={entry.slug} href={`/templates/${entry.slug}`} className="rounded-full border border-[var(--aura-border)] px-3 py-1 text-xs font-semibold">{entry.title}</Link>)}</div></div><div className="mt-8 rounded-3xl bg-white p-6"><h2 className="font-bold">Template sections</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--aura-body)]"><li>Owner policy or goal</li><li>Team responsibility</li><li>Approval process</li><li>Weekly review metric</li><li>Aura workflow location</li></ul></div></Container></section></>; }
